### ISSUE TITLE
Translations using gettext PO

### ISSUE THREAD

**Issue by securearth** [nlogozzo/NickvisionMoney#1]
Translations can be added using gettext module so people can contribute translations in their native language

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2022.11.0-beta2

**Comment by bordam** [comment]
@nlogozzo @zothma We should have two separate strings for "New": one for when it's referred to Group and one for Transaction since in some languages you translate them differently.

**Comment by bordam** [comment]
Also, for Group I would use a separate string too: in the shortcuts dialog it's better to use a plural form in my language.

**Comment by bordam** [comment]
Missing localization in string "Money Account (*.nmoney)" in open account dialog

**Comment by bordam** [comment]
Like Group, Income and outcome need two separate strings in my language: one for the Type in the transaction dialog and one for Overview.

**Comment by securearth** [comment]
> Also, for Group I would use a separate string too: in the shortcuts dialog it's better to use a plural form in my language.

In some languages, both plural and singular form of group have the same word, like in Hindi

**Comment by bordam** [comment]
@securearth Yeah of course, you can still translate the strings the same way.

**Comment by securearth** [comment]
I just tested my Hindi translation and found out that you have hardcoded "Money", and added translation for "About", instead of using the string "About Money". In English, about is used before the app name, but in languages like Hindi, "बारे" is used after the app name, so it would be "Money बारे" or "Money के बारे में", but using the current schema, it is rendered as "बारे Money" and not "Money बारे". I think you should instead use the string "About Money" instead of hardcoding 'Money', you can add a comment there asking to not translate the word 'Money' and just keep it like "Money बारे" (generally whoever learns to translate, is taught on articles on Internet that as a convention you should not translate the app name).

**Comment by nlogozzo** [comment]
FYI Please submit a PR with your translations by Nov 10, 2022 to be included in the V2022.11.0 stable release for this week.

**Comment by nlogozzo** [comment]
@zothma Is also currently fixing the translation context with the changes mentioned here. Once that gets merged, I will be asking current PRs to update their translations to the new context before merging them :)

**Comment by nlogozzo** [comment]
Thank you everyone for your help with translating this application, making it accessible to more people than ever before. A stable release will be released this week by Nov 10, 2022 with your translations :)
I'm closing this issue as completed since the translation infrastructure is complete.
