### ISSUE TITLE
Crashes when trying to create .nmoney file

### ISSUE THREAD

**Issue by RDKRACZ** [nlogozzo/NickvisionMoney#104]
I wanted to try it out but it's impossible as it just crashes.

```
flatpak run org.nickvision.money 

(org.nickvision.money:2): GLib-GIO-CRITICAL **: 23:13:03.700: g_file_get_path: assertion 'G_IS_FILE (file)' failed
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
```

**Comment by nlogozzo** [comment]
It seems as the application is unable to get the file path from the file dialog. Did you disable any filesystem permissions by any chance?

**Comment by nlogozzo** [comment]
Follow Up: Which directory are you trying to create the file in?

**Comment by RDKRACZ** [comment]
>Which directory are you trying to create the file in?

Inside my home documents folder and also on a flash drive.

>Did you disable any filesystem permissions by any chance?

No. It should be worth noting that I'm currently using Cinnamon on Fedora 36. I do have Gnome installed and I will switch to it tomorrow to test this behavior.

**Comment by RDKRACZ** [comment]
I just tested it on another device with Linux Mint Cinnamon and it works fine there.
I suspect the problem is within the file picker itself because it is acting weird on my main computer. I will test if selecting an already existing nmoney file (is it a database?) causes crashes or not.

**Comment by nlogozzo** [comment]
> I just tested it on another device with Linux Mint Cinnamon and it works fine there.
> I suspect the problem is within the file picker itself because it is acting weird on my main computer. I will test if selecting an already existing nmoney file (is it a database?) causes crashes or not.

Definitely sounds like a file picker issue since no one else is experiencing this issue.

The .nmoney is an sqlite3 database file.
