### ISSUE TITLE
Incorrect Currency Symbol Placement for GBP

### ISSUE THREAD

**Issue by yamamech** [nlogozzo/NickvisionMoney#106]
Unlike most European countries, the GBP is written in the same format as the US (i.e., £x,xxx.yy), whereas the application displays it in the European format (x,xxx.yy£). The comma/decimal problem appears correct for the GBP, however the currency symbol should be the other way around.
![image](https://user-images.githubusercontent.com/30635996/205516933-9b9fa621-e281-4606-8c9e-e5c531304bc8.png)

**Comment by nlogozzo** [comment]
Money is getting a backend rewrite soon so hopefully localization kinks will be ironed out in the new backend.

**Comment by fsobolev** [comment]
Fixed in [current beta](https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.1.0-beta1)

![](https://i.imgur.com/MdR7pio.png)
