### ISSUE TITLE
Crash on loading from NAS

### ISSUE THREAD

**Issue by Kaya-Sem** [nlogozzo/NickvisionMoney#107]
I have a Synology NAS, and the application crashes when trying to open a file from there.

- When I move my .nmoney files to my NAS, and try to open them in the application, it crashes and won't open the file.
- When "opening" an account from the main startup menu, and choosing a location and name for it,  on my NAS, the application crashes and the file is not created. 

I have multiple machines and I usually sync things through my NAS, just like my keepassxc database file.
Is this a bug, or a feature? 

_Ubuntu 22.10, Wayland
Files from GNOME
Money V2022.11.1_

**Comment by nlogozzo** [comment]
Should be a problem with flatpak permissions since by default it only has access to your home directory.

See if you can download [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) and change the permissions of Money to have access to the host system.

**Comment by Kaya-Sem** [comment]
> Should be a problem with flatpak permissions since by default it only has access to your home directory.
> 
> See if you can download [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) and change the permissions of Money to have file access to the host system.

Changing the permissions has not fixed it. The application still behaves as it did before. (Tried giving it all permissions, updating everything, rebooting..)

**Comment by nlogozzo** [comment]
> Changing the permissions has not fixed it. The application still behaves as it did before. (Tried giving it all permissions, updating everything, rebooting..)

Can you run the application in the terminal (`flatpak run org.nickvision.money`) and see what error messages are generated when it crashes.

**Comment by Kaya-Sem** [comment]
> > Changing the permissions has not fixed it. The application still behaves as it did before. (Tried giving it all permissions, updating everything, rebooting..)
> 
> Can you run the application in the terminal (`flatpak run org.nickvision.money`) and see what error messages are generated when it crashes.

When opening a file from NAS and when creating one there
`(org.nickvision.money:2): GLib-GIO-CRITICAL **: 14:00:16.569: g_file_get_path: assertion 'G_IS_FILE (file)' failed
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
`

**Comment by nlogozzo** [comment]
I would a couple links of other people have similar issues with other apps and flatpak:
- https://github.com/flathub/org.keepassxc.KeePassXC/issues/49
- https://discuss.pixls.us/t/flatpack-access-nas-drive/31006/3

Maybe you can try one of the suggested fixes. But seems to be like a flatpak permissions issue and the way it's handled. If your on an arch-based distro i recommend install Money from the AUR or building it yourself from source.
