### ISSUE TITLE
Wrong Currency Applied For India

### ISSUE THREAD

**Issue by Xanaxus** [nlogozzo/NickvisionMoney#109]
Instead of Rupee Symbol The Pound symbol is applied.

**Comment by heymisphere** [comment]
Can not reproduce this bug, are you sure you are using Indian locale, like en_IN.UTF-8 (Indian English) or hi_IN.UTF-8 (Hindi India), because a lot of computers in India are set by default to en_GB.UTF-8 or en_US.UTF-8

**Comment by nlogozzo** [comment]
Any issue that may have been should be fixed in [V2023.1.0-beta1](https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.1.0-beta1)
