### ISSUE TITLE
Display Monetary Values With User's Regional Settings

### ISSUE THREAD

**Issue by bordam** [nlogozzo/NickvisionMoney#11]
Gnome control center has a section dedicated to formats that states "Formats are used for numbers, dates, and currencies." Money could automatically select the correct currency based on the user's setting.

**Comment by nlogozzo** [comment]
Will look into this, thanks!

**Comment by nlogozzo** [comment]
Please test [V2022.11.0-beta3](https://github.com/nlogozzo/NickvisionMoney/releases/tag/2022.11.0-beta3)

**Comment by bordam** [comment]
Hmm, it's not working for me

**Comment by bordam** [comment]
When I open the app for the first time, it's nothing. But if I restart it or create an account the symbol becomes $.

Also, why should it be nothing and not €?

**Comment by nlogozzo** [comment]
Boh 🤷‍♂️ that's what I'm trying to figure out haha. What's ur locale code on the computer? it_IT?

**Comment by nlogozzo** [comment]
Ok I'm going to try some things e vediamo cosa succede

**Comment by securearth** [comment]
I built the new version, and to test this functionality, i first edited `~/.config/Nickvision/NickvisionMoney/config.json` and removed the symbol entry (so that the app does not load that setting), and I opened the app and created a new account, it correctly picked up my ₹ symbol

**Comment by nlogozzo** [comment]
@bordam Try downloading and running the .flatpak file from [V2022.11.0-beta3](https://github.com/nlogozzo/NickvisionMoney/releases/tag/2022.11.0-beta3) again and see if it works.
When you open the app, check the Preferences dialog and see if the symbol is set to `$`. If it is, delete all the text in that box and close the dialog. Reopen the dialog and it should be `€`.

**Comment by fsobolev** [comment]
> Try downloading and running the .flatpak file from [V2022.11.0-beta3](https://github.com/nlogozzo/NickvisionMoney/releases/tag/2022.11.0-beta3) again and see if it works.
It works for me (ru_RU.UTF-8, the app correctly sets ₽).

By the way, user region settings affect not only currency, but also numbers. As you can see in GNOME settings, 123,456.78 is valid number for english, but it's not valid for russian for example (123456,78). Currently the app expects numbers in english format, but if I try to put number in russian format, it just cuts the value without any warning (123,45 becomes 123). This behaviour can be very confusing for users. Should I open another issue for this?

**Comment by nlogozzo** [comment]
You can leave it in this issue. I will change the title of the issue to reflect displaying monetary values with regional settings.

**Comment by bordam** [comment]
Tested now, it works flawlessly both with AUR vcs package and flatpak package. Thank you so much!! First time I open the app, if I open preferences currency is still set to nothing, but I don't see it as an actual issue from a usability perspective honestly

**Comment by nlogozzo** [comment]
Great! I'm just going to fix the issue of displaying the monetary values $1,000.52 vs €1.000,52

**Comment by bordam** [comment]
Same problem also applies to dates!!

**Comment by nlogozzo** [comment]
Yes true!

**Comment by nlogozzo** [comment]
Please test [V2022.11.0-beta4](https://github.com/nlogozzo/NickvisionMoney/releases/tag/2022.11.0-beta4)

Input and displaying of monetary values should work in a user's locale settings now.

**Comment by fsobolev** [comment]
It doesn't work properly. I created a new account and saw this:

<img src="https://camo.githubusercontent.com/8f061ff33349c58cdfb711c34194fd0497ff9135fbf1b76ee885daa961d78483/68747470733a2f2f692e696d6775722e636f6d2f654c554d42304e2e706e67" width=400>

Then I've created a transaction for tests.

what value I enter -> what I get
123,45 -> 123,45 🆗 
123.45 -> ,00 ?* 
123 -> 1,23 :x:

* it would be good if the app will ask to enter another value if it doesn't fit the format

**Comment by nlogozzo** [comment]
@fsobolev 
`123.45 -> ,00 ?*` is correct no? Since 123.45 is an invalid amount in your locale. It should be 123.450 to be correct, no?

**Comment by nlogozzo** [comment]
> **Edit**: oh, and also if I delete the currency sign from the value string, it always becomes ",00"

That's weird cause in USA settings if I do 45 it correctly goes to $45.00, hmmm

**Comment by fsobolev** [comment]
> @fsobolev `123.45 -> ,00 ?*` is correct no? Since 123.45 is an invalid amount in your locale. It should be 123.450 to be correct, no?

Both 123.45 and 123.450 are incorrect in my locale (only comma is accepted and only as a separator of the fractional part). My point was this:

> it would be good if the app will ask to enter another value if it doesn't fit the format

Similar to when you leave group description empty when creating new group for example, the dialog is reopened and the app tells the user what's wrong.

**Comment by nlogozzo** [comment]
> 123 -> 1,23 x

Can you see if this is fixed with the latest commit? https://github.com/nlogozzo/NickvisionMoney/commit/3574bdcad291e9e7e3962a3bb865576d4b6339f1

**Comment by fsobolev** [comment]
> > 123 -> 1,23 x
> 
> Can you see if this is fixed with the latest commit? [3574bdc](https://github.com/nlogozzo/NickvisionMoney/commit/3574bdcad291e9e7e3962a3bb865576d4b6339f1)

No changes

**Comment by nlogozzo** [comment]
> No changes

123 is expected to be 123, correct?

**Comment by nlogozzo** [comment]
> * it would be good if the app will ask to enter another value if it doesn't fit the format

That should be fixed in: https://github.com/nlogozzo/NickvisionMoney/commit/361d1ba8424460548d96875a7fd6cb2999f6bbbb

**Comment by fsobolev** [comment]
> That should be fixed in: [361d1ba](https://github.com/nlogozzo/NickvisionMoney/commit/361d1ba8424460548d96875a7fd6cb2999f6bbbb)

Works great.

> 123 is expected to be 123, correct?

Showing 123,00 would be fine too

**Comment by nlogozzo** [comment]
The way the C++ money_put library works is very weird, and requires money values to be formated weirdly to be handled universally. I have to try some things...

**Comment by nlogozzo** [comment]
> 123 -> 1,23 x

@fsobolev If you type `123,00` does it work correctly? The application is supposed to add `,00` to the end if it's not found, but for some reason, it's not doing it.

**Comment by fsobolev** [comment]
> If you type 123,00 does it work correctly? The application is supposed to add ,00 to the end if it's not found, but for some reason, it's not doing it.
123,00 -> 123,00
123,0 -> shows that the value is incorrect

**Comment by fsobolev** [comment]
Since this issue seems complicated, I have a proposal. Let's not rely on locale settings and just expect value string to contain numbers and either one dot or one comma as decimal separator. This way "123,456.78" will be invalid, but both "123456.78" and "123456,78" will be valid no matter what is a user's locale. I think it's acceptable and universal enough, So if it's easier to implement, you will have more time to work on other issues.

**Comment by nlogozzo** [comment]
@fsobolev Try `123` with https://github.com/nlogozzo/NickvisionMoney/commit/49174ebdeb211619fbbfedc7e23e55b57165cb2b

**Comment by fsobolev** [comment]
> @fsobolev Try `123` with [49174eb](https://github.com/nlogozzo/NickvisionMoney/commit/49174ebdeb211619fbbfedc7e23e55b57165cb2b)

No changes.

**Comment by nlogozzo** [comment]
@fsobolev Could you change `src/helpers/moneyhelpers.cpp` to 
```cpp
#include "moneyhelpers.hpp"
#include <sstream>
#include <iostream>

using namespace NickvisionMoney::Helpers;

std::string MoneyHelpers::boostMoneyToLocaleString(boost::multiprecision::cpp_dec_float_50 amount, const std::locale& locale)
{
    std::stringstream builder;
    //Get Amount As String
    amount *= 100.0;
    builder << amount;
    std::string amountAsString{ builder.str() };
    //Reset Builder
    builder.str("");
    builder.clear();
    //Get Amount as Locale String
    builder.imbue(locale);
    builder << std::showbase << std::put_money(amountAsString);
    return builder.str();
}

boost::multiprecision::cpp_dec_float_50 MoneyHelpers::localeStringToBoostMoney(const std::string& localeString, const std::locale& locale)
{
    std::stringstream builder;
    builder.imbue(locale);
    builder << localeString;
    long double value{ 0.00 };
    builder >> std::get_money(value);
    std::cout << localeString << std::endl;
    std::cout << value << std::endl;
    value /= 100;
    return { value };
}

bool MoneyHelpers::isLocaleDotDecimalSeperated(const std::locale& locale)
{
    return std::use_facet<std::moneypunct<char>>(locale).decimal_point() == '.';
}
```

And try to create a transaction with the amount `123` and check the console for an output and send me the output from the console.

**Comment by fsobolev** [comment]
@nlogozzo 

```
123 ₽,00
123
```

**Comment by nlogozzo** [comment]
Ah i see the issue tho! Thank you for this!

**Comment by nlogozzo** [comment]
@fsobolev Please try https://github.com/nlogozzo/NickvisionMoney/commit/7a257edc2c170ccfd8d37c1d77e0da161ed2eed9

**Comment by fsobolev** [comment]
> @fsobolev Please try [7a257ed](https://github.com/nlogozzo/NickvisionMoney/commit/7a257edc2c170ccfd8d37c1d77e0da161ed2eed9)

Crash on attempt to create/edit transaction with any value.

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::erase: __pos (which is 32) > this->size() (which is 9)
Aborted (core dumped)
```

**Comment by nlogozzo** [comment]
Ok I switched to the Boost.Locale library for localization and hopefully the formatting works a lot better for monetary values. Try the latest commit and let me know how it looks. https://github.com/nlogozzo/NickvisionMoney/commit/a3b8536bebbbc36dbcfe6bb11d0e07f8911a093e

**Comment by bordam** [comment]
That's great, latest commit works correctly for me! At this point, a good thing would be to automatically convert numpad's . to a whatever symbol separates integers and decimals (e.g. comma), like gnumeric does.

**Comment by nlogozzo** [comment]
> That's great, latest commit works correctly for me! At this point, a good thing would be to automatically convert numpad's . to a whatever symbol separates integers and decimals (e.g. comma), like gnumeric does.

That may be a little hard to do...I'll look into it

**Comment by nlogozzo** [comment]
Closing this issue as it's been implemented. 
Thank you everyone for your endless testing, feedback, and patience :)

**Comment by nlogozzo** [comment]
All of the changes with the new Boost.Locale library can be found in the latest beta: https://github.com/nlogozzo/NickvisionMoney/releases/tag/2022.11.0-beta5
