### ISSUE TITLE
Toggle sidebar icon is missing

### ISSUE THREAD

**Issue by vanillajonathan** [nlogozzo/NickvisionMoney#110]
I use the Flatpak version on Ubuntu 22.10.

The "Toggle Sidebar" icon is missing and instead shows a default icon.

**Comment by fsobolev** [comment]
I installed Money from Flathub in virtual machine with Ubuntu 22.10. Everything is fine by default. Do you use custom icon theme? Then it should be reported to the developer of the icon theme that `sidebar-show-symbolic` icon is missing. It's not only used by Money, other apps, including Nautilus, use it too.

**Comment by vanillajonathan** [comment]
Yes, I was using a custom icon theme. When switching back to the Adwaita icon theme the icon is present as expected.
