### ISSUE TITLE
Make group description optional

### ISSUE THREAD

**Issue by vanillajonathan** [nlogozzo/NickvisionMoney#111]
When creating a group you are required to specify both a name and a description. I think the description should be optional.

**Comment by nlogozzo** [comment]
![WinUI](https://user-images.githubusercontent.com/17648453/210123583-a0336717-8d88-473d-a430-67df7e0e68d3.png)
![GNOME](https://user-images.githubusercontent.com/17648453/210123590-d8829783-3e80-40a0-82c0-11215a2a22d2.png)
https://github.com/nlogozzo/NickvisionMoney/commit/945b47aefef3b229fc0da7618fe02722b3dd17d9

**Comment by nlogozzo** [comment]
Fixed in [V2023.1.0-beta2](https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.1.0-beta2)
The update is being published to flathub-beta now and should be available in 10-30 minutes :)
