### ISSUE TITLE
Use CSS colors for overview labels and not style classes

### ISSUE THREAD

**Issue by vanillajonathan** [nlogozzo/NickvisionMoney#112]
In the overview, the total amount of money in a account is shown in green even if the sum is negative.

**Comment by nlogozzo** [comment]
The Total label is shown in Blue never in green/red.

**Comment by vanillajonathan** [comment]
The total label uses the "accent" CSS class hence it can get another color when using a different theme.

https://github.com/nlogozzo/NickvisionMoney/blob/main/src/ui/views/accountview.cpp#L36

I use [Gradiance](https://github.com/GradienceTeam/Gradience) to set another theme.

Adwaita provides named colors.
https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/named-colors.html#palette-colors

**Comment by fsobolev** [comment]
`@accent_color` is different in Adwaita for light and dark styles, so using one of named blue colors breaks expected coloring for those who don't use custom theme. My suggestion is to place [please don't theme](https://stopthemingmy.app/) badge and add custom css classes that will not do anything by default but that will make it possible for users of custom themes to easily recolor all needed elements in `$XDG_CONFIG_HOME/gtk4/gtk.css` (and add instruction in README on how to do this). I will work on this if you think it's acceptable, @nlogozzo

**Comment by nlogozzo** [comment]
> `@accent_color` is different in Adwaita for light and dark styles, so using one of named blue colors breaks expected coloring for those who don't use custom theme. My suggestion is to place [please don't theme](https://stopthemingmy.app/) badge and add custom css classes that will not do anything by default but that will make it possible for users of custom themes to easily recolor all needed elements in `$XDG_CONFIG_HOME/gtk4/gtk.css` (and add instruction in README on how to do this). I will work on this if you think it's acceptable, @nlogozzo 

I think that's a good solution. Go ahead! :)
