### ISSUE TITLE
Amount does not use Gtk InputHints

### ISSUE THREAD

**Issue by vanillajonathan** [nlogozzo/NickvisionMoney#123]
Set the input hints for the Amount to number.

[set_input_purpose](https://docs.gtk.org/gtk4/method.Text.set_input_purpose.html)
[GTK_INPUT_PURPOSE_NUMBER](https://docs.gtk.org/gtk4/enum.InputPurpose.html#number)

**Comment by nlogozzo** [comment]
Fixed in [V2023.1.0-beta1](https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.1.0-beta1)
