### ISSUE TITLE
New Account Setup Dialog

### ISSUE THREAD

**Issue by bordam** [nlogozzo/NickvisionMoney#128]
I think outcomes are created more often than incomes, so why not either set outcome as default or add an option to choose the default transaction type?

**Comment by zothma** [comment]
I think it would be quite an interesting idea indeed

**Comment by nlogozzo** [comment]
I'm thinking of creating a whole Account Setup dialog when you make a new account. In this dialog will be currency (locale or custom), default transaction (income vs expense), and other customizable options. Of course, this dialog will be able to be accessed at any time from the account view to change settings whenever.

**Comment by fsobolev** [comment]
> I'm thinking of creating a whole Account Setup dialog when you make a new account.

A mockup (made in Python, will rewrite in C# when the app will be ported).

![](https://i.imgur.com/X4nWrwD.png)
![](https://i.imgur.com/YLtQFfa.png)

**Comment by vanillajonathan** [comment]
The country flag emojis could be used for accounts in different countries.

Example:
- 🇺🇸 My American account
- 🇨🇭 My Swiss account

See #118

**Comment by fsobolev** [comment]
> The country flag emojis could be used for accounts in different countries.
> 
> Example:
> 
> * 🇺🇸 My American account
> * 🇨🇭 My Swiss account
> 
> See #118

https://github.com/nlogozzo/NickvisionMoney/discussions/120#discussioncomment-4326880
> Well you will be able to add any emoji wherever you want in account name

Users who don't have accounts in multiple jurisdictions, or who don't use multiple currencies, or who track money not from real world, don't need this, so this feature is redundant.

**Comment by vanillajonathan** [comment]
> Users who don't have accounts in multiple jurisdictions, or who don't use multiple currencies, or who track money not from real world, don't need this, so this feature is redundant.

Well it could be an optional feature that those people don't have to use. It could also include icons for crypto currencies maybe.

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/211132831-f4608e80-5c78-41eb-b3c1-5c1450e30162.png)

Major developments on [account-setup-dialog branch](https://github.com/nlogozzo/NickvisionMoney/tree/account-setup-dialog). GNOME dialog is coming soon :)

Feel free to play around with it BUT DO NOT USE IMPORTANT `.nmoney` FILES as the API is unstable and could break/corrupt something

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/211135440-db8bb958-82b0-4fa3-86cb-768934f4d357.png)
 
Courtesy of @fsobolev :)

**Comment by vanillajonathan** [comment]
And if you don't use a custom currency, so you use your system reported currency, then you change your system settings, what happens then?
Does the currency for the account change to the new system settings?

I think it would be better to avoid the the term "custom currency", remove the "Use Custom Currency" switch, and always require the user to specify a currency, however that currency can be set by the default to the system reported currency.

**Comment by bordam** [comment]
> And if you don't use a custom currency, so you use your system reported currency, then you change your system settings, what happens then? Does the currency for the account change to the new system settings?
> 
> I think it would be better to avoid the the term "custom currency", remove the "Use Custom Currency" switch, and always require the user to specify a currency, however that currency can be set by the default to the system reported currency.
AFAIU once the currency is set for an account it’s not affected by system locale at all

**Comment by vanillajonathan** [comment]
> AFAIU once the currency is set for an account it’s not affected by system locale at all

Good, it shouldn't, but it isn't clear, hence why I think it would be better to remove any ambiguity by removing the Use Custom Currency switch.

**Comment by nlogozzo** [comment]
The `Use Custom Currency` feature as shown allows a user to change their currency symbol for the account. For example, if my system reports `$` and I want to use `€` i can change that here.

However, Money still uses the system locale to determine the number formating used. For example, if i change my currency symbol to `€`, but I'm in the USA, my nunbers will be €1,000.00. Whereas if I'm in France and I change ny symbol to `$`, my numbers will be 1.000,00 $

**Comment by nlogozzo** [comment]
If `Use Custom Currency` is off, the account will use the symbol from the current locale just as before, and any changes to system locale will be seen in the account, just as before.

**Comment by fsobolev** [comment]
> > AFAIU once the currency is set for an account it’s not affected by system locale at all
> 
> Good, it shouldn't, but it isn't clear, hence why I think it would be better to remove any ambiguity by removing the Use Custom Currency switch.

It's not like people usually change locale after OS is installed, so I don't think most of users will even care about what will happen if locale is changed - but if they will care, they will find out, without any destructive changes, that the app tries to get currency and numbers format from locale every time it starts. And if a user wants to use something different than a system currency, only then they will need to do extra actions to change currency to whatever cryptodabloons they want.
And anyway, even without experiments with system locale, users will be able to know how everything works in the app by reading documentation (that I will add soon).

**Comment by nlogozzo** [comment]
> The country flag emojis could be used for accounts in different countries.
> 
> Example:
> 
> * 🇺🇸 My American account
> * 🇨🇭 My Swiss account
> 
> See #118

![image](https://user-images.githubusercontent.com/17648453/211153087-8359fb38-f9bd-4b12-ab7e-a2f2a968d36c.png)

Emojis are fully supported in the AccountName on GNOME and WinUI for this :)

**Comment by nlogozzo** [comment]
Although toggles are not shown in the dialog, Money will remember `Show Groups` and `Sort First To Last` toggle setting on an individual account basis now.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.1.0-rc1
