### ISSUE TITLE
Unable to select new date if current date is the same day of a different month

### ISSUE THREAD

**Issue by bordam** [nlogozzo/NickvisionMoney#129]
https://user-images.githubusercontent.com/95233098/206420054-3d09a1f3-839f-4abe-a25e-8e7d1d0c1b50.mp4

Ofc you can workaroud this by selecting another date first, but this way the experience is not the best

**Comment by nlogozzo** [comment]
I will also update the date when a month/year is changed, but the date stays the same. I just need to bind to other signals.

**Comment by nlogozzo** [comment]
Should be fixed in [V2023.1.0-beta1](https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.1.0-beta1)
