### ISSUE TITLE
"&" in transaction description makes it invisible

### ISSUE THREAD

**Issue by matbme** [nlogozzo/NickvisionMoney#134]
Adding the "&" symbol to a transaction will make its name invisible.

![image](https://user-images.githubusercontent.com/48367298/207046164-3ff0dda7-af30-44be-b1aa-c0282823f905.png)
![image](https://user-images.githubusercontent.com/48367298/207046228-bb989bd5-90f4-4572-b854-5d9467d05577.png)

**Comment by nlogozzo** [comment]
Should be fixed in [V2023.1.0-beta1](https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.1.0-beta1)
