### ISSUE TITLE
Why show the amount using potentiation?

### ISSUE THREAD

**Issue by hrqmonteiro** [nlogozzo/NickvisionMoney#136]
Wouldn't two digits after the dot be sufficient? This looks weird:

![Screenshot from 2022-12-17 14-21-27](https://user-images.githubusercontent.com/17055027/208253763-9dfd553e-0335-4394-920b-f369462518e1.png)

**Comment by nlogozzo** [comment]
This is definitely a bug and the amount should not be displayed like this.
Is it showing like this for all amounts or just the total?

**Comment by hrqmonteiro** [comment]
> This is definitely a bug and the amount should not be displayed like this. Is it showing like this for all amounts or just the total?

It is showing just the total like this

**Comment by nlogozzo** [comment]
Should be fixed in [V2023.1.0-beta1](https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.1.0-beta1)
