### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by bertob** [nlogozzo/NickvisionMoney#139]
As discussed in the Circle review, this app could benefit from a having a more unique name. Some ideas to kick things off:

- Tender
- Stacks
- Ebenezer
- Scrooge
- Dough
- Bucks
- Balance
- Overdraft
- Coins

**Comment by nlogozzo** [comment]
Maybe other language names? I'm italian so:

- Portafoglio = Wallet
- Soldi = Money
- Denaro = Money
- Contanti = Cash

**Comment by fsobolev** [comment]
* Coin Purse
* Porte Monnaie
* Cash Box

**Comment by bertob** [comment]
Non-english words can work, but only in rare cases where the term is somewhat international. At the very least it needs to be easy to pronounce, so definitely not portafoglio :D

**Comment by heymisphere** [comment]
My suggestion: "FinoMan" from "Finance Manager"

**Comment by nlogozzo** [comment]
@bertob I like `Denaro`

Comment from @fsobolev:
> "Denaro" is easy to pronounce and I guess it refers to "dinar" which is a common term in some countries, so if this will work I agree that it's great

**Comment by bertob** [comment]
Denaro could work, yeah.

**Comment by nlogozzo** [comment]
[Goodbye Money, Hello Denaro!](https://github.com/nlogozzo/NickvisionMoney/commit/511de12835a8022decd3f7a8f5c283a7ca3d4b68)

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.1.0-rc1
