### ISSUE TITLE
Hide groups

### ISSUE THREAD

**Issue by brunnogama** [nlogozzo/NickvisionMoney#140]
I think will be better if the Groups could be hide  or minimized on side panel.

**Comment by nlogozzo** [comment]
@fsobolev FYI

Do you mean the whole groups section should be collapsable?
I don't really see this as a useful feature IMO.

**Comment by brunnogama** [comment]
When you have a lot of groups, I think its doesnt looks good and not useful. Could be better if we can minimize it.

Sorry, I cant explain better, my english isnt good.

**Comment by fsobolev** [comment]
Ah I see. When there are a lot of groups the list can be really long, making it hard to navigate to calendar for example. Can be fixed by using Gtk.ScrollWindow for groups list.

**Comment by nlogozzo** [comment]
Fixed in [V2023.1.0-beta2](https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.1.0-beta2)
The update is being published to flathub-beta now and should be available in 10-30 minutes :)

**Comment by nlogozzo** [comment]
This feature was also added to WinUI. Will be available in the next beta:

Groups Shown:
![image](https://user-images.githubusercontent.com/17648453/210158773-8e2eb403-2341-46d7-a270-9217be244260.png)

Groups Hidden:
![image](https://user-images.githubusercontent.com/17648453/210158775-0835f228-c3b0-4f0a-923a-7c3e2a7ffaab.png)
