### ISSUE TITLE
Show all expenses

### ISSUE THREAD

**Issue by brunnogama** [nlogozzo/NickvisionMoney#142]
I think would be nice an overview with all expenses, maybe with a filter (all, week, month, year).
Something like:
- Click on Expenses shows all expenses and one option to choose all, week, month etc
- Click on one group, shows all expenses from that group with options like above. 

Btw, your app is awesome.

**Comment by nlogozzo** [comment]
Thanks :)

All of these specific filters will be added in PDF reports ( #3 ). You'll be able to create custom reports in the ways you mentioned.

**Comment by fsobolev** [comment]
If you're worried that you can't list expenses transactions from specific groups without listing ungrouped transactions, this is fixed in C# rewrite of the app. Beta release is coming hopefully today 🎉
