### ISSUE TITLE
Typo at /Shared/Resources/string.resx

### ISSUE THREAD

**Issue by AsBenDoge** [nlogozzo/NickvisionMoney#150]
Line 185,

```
<data name="Greeting.Night" xml:space="preserve">
	<value>Good Morning!</value>
</data>
```

I'm assuming it's a typo as this is a duplicated data. If it's not the Russian translation has to be updated. (Italian follows English ver.)

**Comment by fsobolev** [comment]
It's not a mistake and Russian translation is correct. In English you can't say "Good night" as a greeting, people say "Good morning" even if the time is 0am-6am. But in Russian it's different (and probably in some other languages too.)
