### ISSUE TITLE
LC_MONETARY is not respected

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [nlogozzo/NickvisionMoney#153]
Pretty much the same issue as #11. 

Everything is shown as GPB, but I'm expecting to see EUR. My `LANG` is `en_GB.UTF-8`, but `LC_MONETARY` is set to `de_AT.UTF-8`. 

![image](https://user-images.githubusercontent.com/15961647/210114801-f018a562-daab-44ec-b61a-e8fabcc57d59.png)

When I start the application, I get the warning `Locale not supported by C library. Using the fallback 'C' locale.`

I'm using version `2023.1.0-beta1` from flathub beta.

**Comment by nlogozzo** [comment]
See: https://stackoverflow.com/a/30892121

What happens if you set both language and format to `de_AT.UTF-8`?

**Comment by SoMuchForSubtlety** [comment]
> What happens if you set both language and format to `de_AT.UTF-8`?

A crash 😄
```
$ flatpak run org.nickvision.money

(process:2): Gtk-WARNING **: 23:20:05.767: Locale not supported by C library.
	Using the fallback 'C' locale.
Registering new type NickvisionMoneyGNOMEViewsMainWindow with parent AdwApplicationWindow
Unhandled exception. System.FormatException: String '31/01/2023' was not recognized as a valid DateOnly.
   at System.DateOnly.ThrowOnError(ParseFailureKind result, ReadOnlySpan`1 s)
   at System.DateOnly.Parse(String s, IFormatProvider provider)
   at NickvisionMoney.Shared.Models.Account..ctor(String path) in /run/build/org.nickvision.money/NickvisionMoney.Shared/Models/Account.cs:line 92
   at NickvisionMoney.Shared.Controllers.AccountViewController..ctor(String path, Localizer localizer, EventHandler`1 notificationSent) in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/AccountViewController.cs:line 92
   at NickvisionMoney.Shared.Controllers.MainWindowController.AddAccount(String path, Boolean showOpenedNotification) in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/MainWindowController.cs:line 131
   at NickvisionMoney.GNOME.Views.MainWindow.<>c__DisplayClass58_0.<CreateRecentAccountRow>b__0(Button sender, EventArgs e) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/MainWindow.cs:line 550
   at GObject.Signal`1.<>c__DisplayClass2_1.<Connect>b__1(Value[]& _)
   at GObject.Object.ClosureHelper.MarshalCallback(Closure closure, Value returnValue, UInt32 nParamValues, Value[] paramValues, Nullable`1 invocationHint, Nullable`1 marshalData)
   at GObject.ClosureMarshalCallHandler.<.ctor>b__2_0(IntPtr closure, IntPtr returnValue, UInt32 nParamValues, ValueData[] paramValues, IntPtr invocationHint, IntPtr marshalData)
```

**Comment by SoMuchForSubtlety** [comment]
Creating a new account works and correctly uses Euros. But I'd like to leave my language set to English and still use Euros.

**Comment by nlogozzo** [comment]
> A crash 😄

This is a separate issue. @fsobolev It has to do with 
```csharp
Date = DateOnly.Parse(readQueryTransactions.GetString(1), new CultureInfo("en-US", false))
``` 
on line 103 of the current `Account.cs`. Maybe we shouldn't set the culture info to US here since previous versions of Money could have non US formated dates.

**Comment by nlogozzo** [comment]
> Creating a new account works and correctly uses Euros, but I'd like to leave my language set to English and still use Euros.

See #128. We are adding settings to an account where you could change the currency used by the account from Money itself.

**Comment by SoMuchForSubtlety** [comment]
> See #128. We are adding settings to an account where you could change the currency used by the account from Money itself.

That's good to hear, but I think defaulting to the correct currency would improve the user experience. `locale -k currency_symbol` returns `"€"` as expected, so I don't think my settings are broken.

**Comment by nlogozzo** [comment]
> so I don't think my settings are broken.

The currency_symbol is displayed as `€` since that was you have your formats set to `de_AT.UTF-8`. But since your language is `en_GB.UTF-8` when an application tries to load the locale, it combines the two and tries to find `en_AT.UTF-8` which is not a valid C locale in any program, hence why it doesn't display correctly.

**Comment by nlogozzo** [comment]
> > A crash 😄
> 
> This is a separate issue. @fsobolev It has to do with
> 
> ```cs
> Date = DateOnly.Parse(readQueryTransactions.GetString(1), new CultureInfo("en-US", false))
> ```
> 
> on line 103 of the current `Account.cs`. Maybe we shouldn't set the culture info to US here since previous versions of Money could have non US formated dates.

I added a try catch block to loading the date.
It will first try to load using the en_US which newer Money files will be formated in and if that fails it will try to parse the date with the current locale.
```csharp
try
{
    transaction.Date = DateOnly.Parse(readQueryTransactions.GetString(1), new CultureInfo("en-US", false));
}
catch
{
    transaction.Date = DateOnly.Parse(readQueryTransactions.GetString(1));
}
```
I've also made it so AddTransaction and UpdateTransaction save dates in en_US format in the database from now on as well.
https://github.com/nlogozzo/NickvisionMoney/commit/d11c534ecb4ae6995d2799a8a4edab5656eb407a

**Comment by fsobolev** [comment]
> Maybe we shouldn't set the culture info to US here since previous versions of Money could have non US formated dates.

That's exactly the reason I added CultureInfo. Without this I got crashes when I tried to open files with mixed dates.

**Comment by nlogozzo** [comment]
> > Maybe we shouldn't set the culture info to US here since previous versions of Money could have non US formated dates.
> 
> That's exactly the reason I added CultureInfo. Without this I got crashes when I tried to open files with mixed dates.

Yeah i realized that too. Hence I added the try catch so it can parse both forms of a date if needed.

But what do we do with something like 
1/2/22

That could be Jan 2 or Feb 1 depending on the way you look at it.

Should we parse with the current culture first and then if it throws an error try en_US format?

**Comment by fsobolev** [comment]
> Should we parse with the current culture first and then if it throws an error try en_US format?

Idk how it should be implemented in code, but I think that the app should look at the date and if it's not in en_US format rewrite it immediately. I guess this is the best way to fix all possible problems with dates formats.

**Comment by nlogozzo** [comment]
Ok @SoMuchForSubtlety
`Unhandled exception. System.FormatException: String '31/01/2023' was not recognized as a valid DateOnly.` is being caused by a bug in the code where updating a transaction does not store the date in en_US format, which is what the Account expects. 

I've fixed this issue for the next beta, however, it means that your `.nmoney` file is bugged.  
As always, `.nmoney` files containing real data should never be used in beta versions for reasons as this.
However, if you need to recover data from that `.nmoney` file, please use [DB Browser](https://sqlitebrowser.org/) and open the `.nmoney` file in there and correct the date formats to en_US format. After that, the file should be able to open in Money.

**Comment by nlogozzo** [comment]
We found a way to support LC_MONETARY individually. Will be added with #233

**Comment by fsobolev** [comment]
@SoMuchForSubtlety could you please tell what is the correct date format for de_AT locale? I mean in real world, not the format that GNOME Settings shows. Because it shows %Y-%m-%d, which seems to be incorrect, probably a bug in GNU libc.

**Comment by SoMuchForSubtlety** [comment]
It's dd.mm.yy or dd.mm.yyyy, but think officially we use ISO 8601.

**Comment by nlogozzo** [comment]
Ah ok, we only ask because GNOME control center shows the format as DD-MM-YYYY but C# reports the format as DD.MM.YYYY
So as long as DD.MM.YYYY is valid that is what will be used by Denaro.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.2.0-beta1
