### ISSUE TITLE
Missing CONTRIBUTING.md?

### ISSUE THREAD

**Issue by kianmeng** [nlogozzo/NickvisionMoney#161]
For those who want to contribute but not familiar with the C# ecosystem.

**Comment by nlogozzo** [comment]
@fsobolev what should we include in this?

**Comment by fsobolev** [comment]
> @fsobolev what should we include in this?

Not necessary in the following order:
- Building instructions for each platform
- Information about resources where to get help or ask questions (issues, discussions, matrix chat)
- Translation instructions (should be moved here from README)
- Code contribution guidelines:
    - Program structure
    - Coding style
    - General recommendations on what should be implemented/avoided when opening a PR with a new feature or bugfix

**Comment by fsobolev** [comment]
> Please include what new comers should contribute to. I thought you were still working on libharu...so include what library and language to use too, please.

I think a more appropriate thing to explain is not *what* newcomers should contribute to, but how to let us know that you're going to implement something, to avoid situations when 2 or more people work on the same thing, and to let us provide some additional instructions if needed before you start (or to let us explain why your contribution won't be accepted so you don't waste time).

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/blob/main/CONTRIBUTING.md
