### ISSUE TITLE
Opened Accounts Overview Page

### ISSUE THREAD

**Issue by nlogozzo** [nlogozzo/NickvisionMoney#162]
From #90:
> A cross account Dashboard (I should note that there should still be a way to separate accounts, just that it is also useful to have a summary of multiple ones)

Maybe we could add a separate tab page that just shows data for all accounts:
- Total amount
- Total income
- Total expense

But I wouldn't really know what else to add to this page. @RuboGubo could you give some suggestions?

**Comment by fsobolev** [comment]
In GNOME UI, we could add something combined with [Adw.TabOverview](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.TabOverview.html)

**Comment by RuboGubo** [comment]
Well, I was thinking of something like a merged version of what the individual accounts have, you would just have to make sure that people still make and use individual accounts.

**Comment by nlogozzo** [comment]
> Well, I was thinking of something like a merged version of what the individual accounts have, you would just have to make sure that people still make and use individual accounts.

Do you mean listing all transactions from all accounts?
Maybe the page could look like old versions of Money did:
![image](https://user-images.githubusercontent.com/17648453/210176715-9b4cd12e-5b1b-4b9c-9141-a904a9bd5fce.png)
Without the actions, new, edit, delete, obviously. But just listing all the information.

**Comment by nlogozzo** [comment]
It could maybe include all the groups, but I don't think that would be useful.

**Comment by fsobolev** [comment]
Ability to filter all transactions by groups could be useful in case a user have same groups on different accounts. But this will require filtering by group names, because IDs can mismatch.

**Comment by nlogozzo** [comment]
WinUI: 
![image](https://user-images.githubusercontent.com/17648453/229404140-bc3ddb90-c493-4842-96d8-fb105a21355f.png)

GNOME to follow :)

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.4.0-rc1
