### ISSUE TITLE
Use the account name instead the full directory on Adwaita Tab

### ISSUE THREAD

**Issue by Krindog7337** [nlogozzo/NickvisionMoney#163]
Maybe it should use just the account name instead the full directory because it can be overflowed if user's have placed the .nmoney somewhere deep in the dir

insetad of this
![image](https://user-images.githubusercontent.com/92032579/210362576-bd46d298-8a62-43aa-98c9-9db93940029d.png)

we can make it like this
![Screenshot from 2023-01-03 21-03-49](https://user-images.githubusercontent.com/92032579/210364425-8f78b252-bc1f-4a6f-bf7f-8dcffa38a386.png)

**Comment by fsobolev** [comment]
As soon as #128 will be implemented, accounts will have user-defined names, so we could show them instead of filenames.

**Comment by fsobolev** [comment]
I just noticed that you use stable version, but in current master (and I guess in the latest beta too) it's already like you asked.

![](https://i.imgur.com/RI7F9fi.png)

But let's the issue be opened until what I described in previous comment will be implemented.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/commit/f5de8afbf946dc6417b775600b48fb6c06e98de4

Fully fixed in `account-setup-dialog` which will be merged later on today. Use #128 to finish tracking.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.1.0-rc1
