### ISSUE TITLE
Current date FG issue

### ISSUE THREAD

**Issue by stpnwf** [nlogozzo/NickvisionMoney#165]
![Screenshot from 2023-01-04 15-22-05](https://user-images.githubusercontent.com/81482539/210624348-f73e70b5-dbb2-4f05-b923-5c9b9ab27b54.png)
I know Gradience is not supported, but is there any chance, this could be patched? I am guessing you are using a color name rather han a variable name.

**Comment by fsobolev** [comment]
I will look what CSS class to add so you can fix this using [CSS overriding](https://github.com/nlogozzo/NickvisionMoney#gnome-theming).

**Comment by stpnwf** [comment]
Awesome, thank you!

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.1.0-beta3
