### ISSUE TITLE
[Bug] Creating new account with the filename of existing account file doesn't clear the data

### ISSUE THREAD

**Issue by fsobolev** [nlogozzo/NickvisionMoney#19]
* Start new account creation
* In file chooser dialog, choose existing .nmoney file
* You will be asked if you want to overwrite the file, agree
* The file is just opened, not overwritten

**Comment by nlogozzo** [comment]
Good catch! Will look into.

**Comment by nlogozzo** [comment]
Please test [V2022.11.0-beta3](https://github.com/nlogozzo/NickvisionMoney/releases/tag/2022.11.0-beta3)

**Comment by fsobolev** [comment]
Now works as expected
