### ISSUE TITLE
Implement Groups and Envelope Budgeting

### ISSUE THREAD

**Issue by nlogozzo** [nlogozzo/NickvisionMoney#2]

**Comment by ovari** [comment]
Does this issue refer to `Categories`? If so, will subcategories and nested categories be implemented? Thanks

**Comment by nlogozzo** [comment]
Yes, it refers to categories as well.
What I'm thinking of doing is implementing a "Groups" section on the AccountView. In this section you can add, edit and delete groups. Groups will have a name, color, and optional monthly balance:
- If users just want to group they're transactions they will create a group with a name, color, and unlimited monthly balance.
- If users would like to use envelope budgeting, they can add a monthly balance to the group
Then from the Transaction POV, the user can select a group when adding/editing a transaction.

**Comment by nlogozzo** [comment]
As far as subcategories and nested categories, I don't know if that will be implemented.
When I think of groups, I see people creating groups such as Travel, Holidays, Groceries, Bills, etc...
If you can provide me with some use cases for subgroups/nested groups I will consider it.

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/199515661-7d6914d8-0fe2-44d8-9107-be3b96557695.png)
![image](https://user-images.githubusercontent.com/17648453/199515721-be4ff93b-9fa9-4713-a1fb-4cd6005d2816.png)

Some progress: adding/editing a group
Just need to allow associating a transaction with a group.

**Comment by ovari** [comment]
> If you can provide me with some use cases for subgroups/nested groups I will consider it.

https://github.com/moneymanagerex/moneymanagerex/issues/1477

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/200148405-f24dedd4-083d-4a27-859a-e159c75d9e65.png)

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/200148407-e6511e4a-2ebd-4891-8c01-c50132019aa2.png)

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2022.11.0-beta1

**Comment by ovari** [comment]
Perhaps your `Group` field is equivalent to the `Class` field in Quicken. The `Class` field can not be nested.

![Quicken Class](https://user-images.githubusercontent.com/17465872/200154766-2658cc76-0dd6-411d-8dbd-29dd4846f86c.png)

Should another field called `Category` be implemented in your Money application? The `Category` field can be nested, i.e. have subcategories, subsubcategories, etc.

`Franked` is a third level category, i.e. `Investment`:`Dividends`:`Franked`.
![Quicken Category](https://user-images.githubusercontent.com/17465872/200154928-d92ff33c-e7f4-43c7-b664-8a6cccb62c17.png)

The `Category` can be linked to a `Line item` on the Tax Return.

The `Category` can also be linked to a `Usual Tax Code`, also known as `VAT` (Value Added Tax) and `GST` (Goods and Services Tax).

Thank you

**Comment by nlogozzo** [comment]
For the way the app is structured, and the ease of use that it is meant to be, we feel as implementing sub-groups isn't in the best interest as of now. We may consider it in the future.
