### ISSUE TITLE
Add action to open new window

### ISSUE THREAD

**Issue by fsobolev** [nlogozzo/NickvisionMoney#201]
Currently in GNOME there are 2 ways to open a new window when the app is running: either using terminal or by opening a file from file manager. Adding a menu option to open a new window will be useful in case a user wants to see 2 or more accounts at the same time on screen without using tabs.

**Comment by nlogozzo** [comment]
Can this be implemented by allowing a user to drag a tab down and out of the tab bar...similar to how a browser works?

**Comment by fsobolev** [comment]
Even if it's possible to make a new window open when a tab is dragged out of the window (currently this does nothing), it's not as accessible as opening a new window from menu. Having "Open new window" in main menu would be natural.

**Comment by fsobolev** [comment]
I think for WinUI, since it doesn't have a menu like in GNOME, the best would be to place a button without a label (just icon) to the left of the settings button.

![](https://i.imgur.com/2sgGfsS.png)

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/211807744-e2a2af6a-4c88-4e6c-a43a-848d77bad32f.png)

WinUI already has support for opening multiple windows out-of-box. You can either middle-click the icon in the taskbar or you can right-click the icon and click the Application name to open a new window.

This is common functionality for all Windows apps, so no changes needed to WinUI.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.2.0-beta2
