### ISSUE TITLE
Slowness with large databases and RAM usage increase indefinitely

### ISSUE THREAD

**Issue by Suork** [nlogozzo/NickvisionMoney#208]
After importing a large number of transactions (~1400) the app becomes slow: it takes around 8 seconds to record a transaction after pressing OK, after 4 seconds the window to add the transaction closes and after 4 more seconds the transaction appears in the list and the app becomes responsive again. Adding or removing filters is also takes exactly the same time, 8 seconds.
When using an account with a small number of transactions the adding of transactions feel instant. When filtering out all the transactions from showing on the list, adding a transaction is also instant.

I have also noticed a RAM usage issue that could be related: when adding a transaction or adding and removing a filter, the amount of RAM used increases and does not decrease. For my large database each addition of a transaction addition increases the RAM usage 200 MB, like it was loading all the database again and not removing the old one and keeps accumulating indefinitely. When opening the app and database, the RAM usage is around 300 MB and I have got to 3 GB of RAM usage by the app.

I'm using the latest beta version 2023.1.0-rc1 and was having the same slowness issue with the stable release 2022.11.1, so I guess the issue may be reproducible. I use standard Fedora Linux 37 (Workstation Edition).

**Comment by nlogozzo** [comment]
This happens because of the way Denaro loads the account information. Every time you make a change to a group/transaction, the entire account is reloaded.

I'm working on a complete overhaul on this system [on this branch](https://github.com/nlogozzo/NickvisionMoney/tree/speed-up)

I'm trying to get it done for tonight and have an RC2 out tomorrow so you can test it, but no promise that it will make V2023.1.0 release. If it doesn't, then definitely V2023.1.1

**Comment by fsobolev** [comment]
@nlogozzo worked hard to improve how the app works. Tests with RC2 showed that now the app is pretty useful even with accounts that have 1000+ transactions. No more memory leak, and long loading is only on an account opening (and it's actually now looks as loading, not just app freeze), any changes after initial loading are instant or at least very fast. There are still lags unfortunately, generally the UI is not as responsive as with small accounts, but it's hard to do anything with this: Gtk.FlowBox with >1000 children is definitely not that fast to draw. I have some ideas how to improve the situation a bit that I will try to implement for 2023.1.1 (no promises tho, I'm not sure it will work). But anyway, I hope now you will be able to use the app with more comfort, @Suork

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.1.0-rc2
