### ISSUE TITLE
Better appdata summary

### ISSUE THREAD

**Issue by bertob** [nlogozzo/NickvisionMoney#228]
The current summary "A personal finance manager" starts with an article, which is [not recommended](https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/App-Metadata). Instead, it should be framed around what people can do with the app, e.g. "Manage your personal finances".

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/commit/22664f7724ed8ed2d4cb002b48b634f89cd0f9fa
