### ISSUE TITLE
Desktop icon does not work

### ISSUE THREAD

**Issue by arejula27** [nlogozzo/NickvisionMoney#229]
After updating to the V2023.1.0 version the desktop icon does not work. The icon is there 
![image](https://user-images.githubusercontent.com/46299278/213164239-a0f0e77a-6964-4dbb-8f68-36cd3cae51db.png)
But when clicking it does not open the app. The desktop file is:
![image](https://user-images.githubusercontent.com/46299278/213164356-847196db-6bbe-4696-981b-e9a8363f9e00.png)

When trying the command on the terminal the output is 
```bash
➜  ~ % /app/opt/org.nickvision.money/NickvisionMoney.GNOME
zsh: no such file or directory: /app/opt/org.nickvision.money/NickvisionMoney.GNOME
```

**Comment by nlogozzo** [comment]
Are you using Fedora Silverblue or Workstation?

**Comment by arejula27** [comment]
Is manjaro, however the terminal is on a fedora distrobox

**Comment by arejula27** [comment]
when i tried the command is on my main terminal not distrobox of course

**Comment by nlogozzo** [comment]
FYI @fsobolev

**Comment by nlogozzo** [comment]
My development box is on Windows so all the linux stuff I do is on WSL through the terminal. 

Let me check my old linux machine and see what happens when I install through flatpak on there if it works or not...

**Comment by nlogozzo** [comment]
@arejula27 Another quick question...you installed via `flathub` or via the flatpak file on the releases page?

**Comment by nlogozzo** [comment]
Everything works fine for me on Fedora 37 Workstation.
Must be something different with the paths used on Manjaro that we didn't account for. But that doesn't make sense since it's flatpak and it's all the same.

There is an AUR package by @bordam that will hopefully be updated soon: https://aur.archlinux.org/packages/nickvision-money
I'd like to see if that works or not.

In the meantime, let's wait for @fsobolev since he's my linux guy.

**Comment by bordam** [comment]
AUR package will be updated within 1 hour under the name "denaro". As for the git version, the current "nickvision-money" package will be merged with the "denaro" package

**Comment by nlogozzo** [comment]
@bordam Grazie buonuomo :)

**Comment by arejula27** [comment]
it works

**Comment by nlogozzo** [comment]
> it works

@arejula27 The AUR package? 
Well, that is still on the old Money 2021.11.1 version. Let's see what happens with `Denaro`.

**Comment by nlogozzo** [comment]
Like I said that's the old version. Let's see what happens when it's updated.

**Comment by bordam** [comment]
The new version is on the aur: https://aur.archlinux.org/packages/denaro

**Comment by nlogozzo** [comment]
@bordam Will users of `nickvision-money` package be automatically upgraded, or at least notified of the new package?

**Comment by bordam** [comment]
I'm not sure what will happen if I add nickvision-money to the provides array though, I'll try and I'll let you know

**Comment by nlogozzo** [comment]
@arejula27 Uninstaller flatpak version and install the `denaro` AUR package and let me know if fhe desktop file works there.

**Comment by arejula27** [comment]
Looks the new aur package works great

**Comment by bordam** [comment]
No, even using provides users won't have an update notification. I don't think there's much we can do to fix this...

**Comment by nlogozzo** [comment]
> No, even using provides users won't have an update notification. I don't think there's much we can do to fix this...

Non ti preoccupare...like you said they'll probably see the new name and that `nickvision-money` is out of date and realize that theyre might be a new package. I'll add to future release notes that there is a new AUR package as well.

**Comment by nlogozzo** [comment]
> It looks the new aur package works great

Great! 
I'll leave this issue open anyway to see about the flatpak .desktop file issues on Manjaro. 
It works on Fedora and Ubuntu no problem...but i'd like it to work on Arch/Manjaro too since many people prefer flatpak.

**Comment by fsobolev** [comment]
> The icon is there

But it's not Denaro icon. Here the name is "Money", but in the desktop file you show it's "Denaro" like it should be.
Something is messed up in your setup. I just got an update for stable version and the desktop file changed like it should be and it works.

> When trying the command on the terminal the output is

Of course, because the command points to the file in sandbox. What will work is
```
flatpak run --command=/app/opt/org.nickvision.money/NickvisionMoney.GNOME org.nickvision.money
```

**Comment by arejula27** [comment]
Reinstalling via flathub fixed it, looks like the update messed up
