### ISSUE TITLE
Groups functionality not working in accounts created by older versions of Money

### ISSUE THREAD

**Issue by securearth** [nlogozzo/NickvisionMoney#23]
So, I started using this application as soon as I saw it on reddit, and created my accounts. The older versions did not have groups functionality. Seeing the development of groups functionality, while testing the new git versions, it crashed if i tried to create a new group. At that time, I thought that maybe it is just being implmeneted so not currently stable, but now i got to know that the the feature has been implemented, but still it crashes when i try to create a new group in accounts created by older version of money. I tried makinga new account, and i was able to create groups in that new account. This is the error which i get when creating new group:
```
terminate called after throwing an instance of 'SQLite::Exception'
  what():  table groups has no column named balance
```

**Comment by securearth** [comment]
According to my understanding, the previous sqlite databases schema did not include the 'balance' column (planned for envelope budgeting), but the new accounts have that.
To mitigate it, you can add some code, so that if that column does not exist (meaning that it was created by some older version of money), it creates new column

**Comment by securearth** [comment]
I just opened the new and old databases in a gui sqlite viewer, and found out that the groups table in newer database has a column called balance, while the name in older database is 'allowance'

**Comment by securearth** [comment]
Also a small information: this old database was created when you were still developing the groups functionality but it was not completed

**Comment by nlogozzo** [comment]
That's why it's not working then, i changed from allowance to balance in development before the beta.

I only recommend running stable/beta versions with your account files to avoid this from happening again. 
The main branch is always in development and is meant for strictly testing.

**Comment by nlogozzo** [comment]
If you can, delete the groups table in the old database file and try it with a beta version in the releases section. It should work there.

**Comment by securearth** [comment]
Never mind, i can just open it in a gui sqlite program and rename the column by myself

**Comment by securearth** [comment]
Also I would keep this in mind to not use git versions directly
