### ISSUE TITLE
Currency code not saved

### ISSUE THREAD

**Issue by vanillajonathan** [nlogozzo/NickvisionMoney#231]
The currency code in the account dialog does not seem to get saved.

**Comment by nlogozzo** [comment]
Duplicate of https://github.com/nlogozzo/NickvisionMoney/issues/225

**Comment by nlogozzo** [comment]
Please look for already opened issues before creating new ones :)

**Comment by vanillajonathan** [comment]
I also experienced the issue with that the **currency symbol** did not get used until I restarted, but I restarted and **currency code** it does still not seem to be persisted.

I think this is a different bug.

**Comment by nlogozzo** [comment]
That's also part of #225. 

It's all fixed in #224. Once that gets merged, I'm thinking of releasing a 2023.1.1 bugfix release today.
