### ISSUE TITLE
Respect LC_TIME and LC_MONETARY

### ISSUE THREAD

**Issue by vanillajonathan** [nlogozzo/NickvisionMoney#233]
When I export to PDF the it says "Generated: 1/18/2023 1 18 PM", I would like this to be "Generated: 2023-01-18 13:18".

The date for the transactions are displayed as "1/18/2023" I would like this to be "2023-01-18".

**Comment by nlogozzo** [comment]
The locale is being respected. If you are getting "Generated: 1/18/2023 1 18 PM" that means your `LANG` is en_US and that's how we format dates in US. 
If you wanted something like "Generated: 2023-01-18 13:18", you'd need a `LANG` that supports that format.

Everything does follow locale time and date, it's just that you're using the wrong locale, since for `en_US` that's the correct format.

Try something like `en_GB`

**Comment by vanillajonathan** [comment]
I have the language set to English (because I want the user interface in English), but I have another locale set for `LC_ADDRESS`, `LC_NAME`, `LC_MONETARY`, `LC_PAPER`, `LC_IDENTIFICATION`, `LC_TELEPHONE`, `LC_MEASUREMENT`, and `LC_TIME`.

Please don't use `LANG` for everything. Use `LC_TIME`.

**Comment by nlogozzo** [comment]
> Please don't use LANG for everything. Use LC_TIME.

That's out of my control. C# (as well as C++) uses `LANG` when generating `CultureInfo`. 

As I said, for now, your best bet is to use `en_GB`, to have English but with European style formats.

**Comment by vanillajonathan** [comment]
I think you can do:

```csharp
var lc_time = Environment.GetEnvironmentVariable("LC_TIME");
var culture = new CultureInfo(lc_time, false);
```

**Comment by nlogozzo** [comment]
Yeah we can probably do that.

**Comment by nlogozzo** [comment]
The only problem is, on Windows these variables don't exist. And remember the application is cross-platform now. So we'd have to work around that.

Also if just LANG is set, do these variables exist? I guess if `Environment.GetEnvironmentVariable` is null we can default back to CultureInfo with LANG.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.2.0-beta1
