### ISSUE TITLE
GTK: Clear amount field on click

### ISSUE THREAD

**Issue by Diegovsky** [nlogozzo/NickvisionMoney#237]
It is annoying to have to clear the Amount field everytime I add a new expense/income.

When editing text input fields, it is common in Gtk to select the whole input on click and use a placeholder in the new transaction case.

Also, could you remove the currency name from the input field? I think it makes more sense to put somewhere else

**Comment by nlogozzo** [comment]
👍

> Also, could you remove the currency name from the input field? I think it makes more sense to put somewhere else

Any suggestions on where else to put it?

**Comment by Diegovsky** [comment]
Hey, good to know you agree :)

WRT the currency name, I think you can make so it is there, but it is not editable/selectable. I think there are widgets in Adw that do this, but if not, I found this stackoverflow answer to be very insightful: [link](https://stackoverflow.com/questions/40074977/how-to-format-the-entries-in-gtk-entry)

**Comment by fsobolev** [comment]
> I think you can make so it is there, but it is not editable/selectable.

But it's not editable in the latest stable. Don't you use 2022.11.x by chance?

**Comment by nlogozzo** [comment]
> But it's not editable in the latest stable. Don't you use 2022.11.x by chance?

@Diegovsky ^

This is what it looks like in the current stable:
![image](https://user-images.githubusercontent.com/17648453/213221515-9bd778fd-9cd3-4fd2-b195-6e0a897b39bb.png)

**Comment by Diegovsky** [comment]
Oh yeah, I am most likely in an older version. I apologize for that, please ignore what I said about the currency name :)

**Comment by nlogozzo** [comment]
The new 2023.1.0 stable should be available in `flathub`
OR
If you are using arch/manjaro there is a new AUR package: `denaro` please remove the old `nickvision-money` package

**Comment by Diegovsky** [comment]
just got the new version from flathub, although I'm on arch :)

**Comment by nlogozzo** [comment]
`Adw.EntryRow` does not have placeholder text but I will make it so that anytime you active the entry, it will select all of the text

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/213255432-04df6846-f512-4886-a8a2-5414567d075c.png)

Looks like it's not a good design to implement this feature :/

**Comment by fsobolev** [comment]
It's not a `Gtk.Entry`, but an `Adw.EntryRow` which doesn't have a placeholder

**Comment by Diegovsky** [comment]
That is a bummer, hopefully future versions of libadwaita will have this
