### ISSUE TITLE
add desktop categories and keywords

### ISSUE THREAD

**Issue by iman-salmani** [nlogozzo/NickvisionMoney#248]
hi
# Categories
Currently application does not specify categories so desktop application menu setting this in Others tab.

![Screenshot from 2023-01-19 08-06-52](https://user-images.githubusercontent.com/32843050/213357390-e03178da-eb95-40fd-966b-456385f431a8.png)

## my suggestion
i added this values for categories:
`Categories=Office;Finance;`
https://specifications.freedesktop.org/menu-spec/latest/apas02.html

![Screenshot from 2023-01-19 08-08-34](https://user-images.githubusercontent.com/32843050/213357864-90af956f-7015-4ff9-97b8-1a004c7fc0ba.png)

# Keywords
i think adding some keywords might be helpful for finding app with desktop search.
like money keyword for now gnome gives to me this 💰.
> finance keyword works because of application comment.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/commit/208f3e787e5bcbd1137041508ff56a242b378afb

But i'm sure the `keywords` should probably be added as strings to translate, right? @fsobolev

**Comment by fsobolev** [comment]
Right. And we could use more keywords.
`money;finance;wallet;GTK;nickvision;`

**Comment by nlogozzo** [comment]
I'll let you take care of that haha 😆
