### ISSUE TITLE
[WinUI] Date button in Transaction Dialog doesn't use locale format

### ISSUE THREAD

**Issue by fsobolev** [nlogozzo/NickvisionMoney#251]
![](https://i.imgur.com/JZVd4Hb.png)

20.01.2023 is correct for ru-RU, 1/20/2023 isn't

**Comment by nlogozzo** [comment]
For my reference:

https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.calendardatepicker?view=winrt-22621#formatting-the-selected-date

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/commit/33d441ec14b7410523dc061a25719badd2519764

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.2.0-beta1
