### ISSUE TITLE
Import of QIF files created by KMyMoney doesn't work

### ISSUE THREAD

**Issue by TheJanzap** [nlogozzo/NickvisionMoney#255]
I'm currently using KMyMoney to manage my finances, but I wanted to give Money/Denaro a shot, so I exported some of my transactions into a QIF file and used Denaro to import it, but it always shows 0 transactions imported.

Version: 2023.1.0 (Windows x64)

**Steps to reproduce**
1. Download and install KMyMoney and create a new file (I chose the US - Base - Simple template)
2. Create a new bank account and some transactions
3. Select File -> Export... -> QIF
4. Select the bank account with the transactions on it, make sure both "Categories" and "Account" are ticked and exportz to QIF
5. Switch to Denaro and import the QIF

Expected result: The transactions shoud be imported into Denaro.
Actual result: "0 transactions imported from file"

I've included the QIF I've used for further testing. [sample.QIF.txt](https://github.com/nlogozzo/NickvisionMoney/files/10475106/sample.QIF.txt)

It would be very handy if this style of QIF could be supported to make switching to Denaro easier!

**Comment by nlogozzo** [comment]
Will be fixed in #286 

NOTE: QIF files must have dates in US format. OFX files must have dates in YYYYMMDD format (as per document specifications).

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.2.0-rc1-f1
