### ISSUE TITLE
Manually Sort Groups

### ISSUE THREAD

**Issue by bordam** [nlogozzo/NickvisionMoney#26]
Is there a way to sort groups? Maybe drag & drop could be implemented to do this

**Comment by nlogozzo** [comment]
Groups are sorted by the order they are created. Would alphabetical order be better?

**Comment by bordam** [comment]
Having a way to manually sort them would be best. Still, imo alphabetical order would be better than creation order. But we should ask more people maybe?

**Comment by nlogozzo** [comment]
Should be fixed in https://github.com/nlogozzo/NickvisionMoney/commit/e4eca12bb711eb19c14683a0e4a86502c55694d1

**Comment by bordam** [comment]
Yes, groups are now sorted alphabetically. If you agree, we can leave this issue open for manual sorting groups

**Comment by nlogozzo** [comment]
Unfortunately, I don't think I will be implementing manually sorting of groups as it will require me to rework indexes of groups in the sql database and save that order everything time a user changes the order of a group and I just don't have the manpower to implement that feature right now. For V2022.11.0, groups will be sorted alphabetically and in the future if I have time I will reopen this issue.
