### ISSUE TITLE
BUG - Importing transactions from CSV fails with no error message.

### ISSUE THREAD

**Issue by Tkdefender88** [nlogozzo/NickvisionMoney#262]
When importing a csv file of transactions the Money accepts the file and reads 0 transactions

A look at what the csv file is that I'm trying to import (anonymized for privacy but the format is still the same)

![image](https://user-images.githubusercontent.com/15901945/214619605-b99ead69-4db3-4ec8-9a0f-7d509e4c8572.png)

When using Actions > Import From CSV > select file 

This is the result. Occurs for both the anonymous and non-anonymous csv file

![image](https://user-images.githubusercontent.com/15901945/214619878-68294e40-f9e4-45a0-9456-e0fb86537b01.png)

What I expect to happen is for transactions to be imported from the file and populate the transactions pane.

**Comment by nlogozzo** [comment]
CSV is not a universal file format. 
Each CSV file can contain a different amount of columns with different information and different delimiters and we cannot account for them all.

The CSV column format used by Denaro is with `;` as the delimiter (not `,`):
```csv
ID;Date (en_US Format);Description;Type;RepeatInterval;RepeatFrom (-1=None,0=Original,Other=Id Of Source);RepeatEndDate (en_US Format);Amount (en_US Format);RGBA;Group(Id Starts At 1);GroupName;GroupDescription
```

To make it easier you can take your blank account in Denaro and click the `Actions` menu and export the account as CSV. Then open that exported CSV and fill in the information you'd like to import and then go back to Denaro and import that new CSV file.

**Comment by fsobolev** [comment]
From user manual:

> Denaro CSV (.csv)
>
>❗ While CSV is a common format and some banks allow their users to export information as CSV, these files are in fact tables that can contain arbitrary data. Importing a CSV file created in other program will fail, because its data will not be compatible with what Denaro tries to get from a file. The purpose of CSV import/export is to provide a way to add data to an account using external programs such as text editors and office suites. Import will only add new transactions without overriding existing ones. If you want to create a CSV file manually, this is the header that includes all columns Denaro expects to find:
>
> `ID;Date;Description;Type;RepeatInterval;RepeatFrom;RepeatEndDate;Amount;RGBA;Group;GroupName;GroupDescription`
>
> Date, RepeatEndDate and Amount should be in English (US) format (MM/DD/YYYY for dates and 123,456.78 for the amount). RepeatFrom is used for repeat transactions (see Repeat Interval in transaction page for details) and should be either an Id of source transaction or 0 if it's a source transaction or -1 if it's not repeat transaction

**Comment by nlogozzo** [comment]
Extra Note: `Amount` for the transaction should always be positive. The `TransactionType` of `Income (0)` or `Expense (1)` will determine whether it is added or subtracted to the total.

@fsobolev Maybe we should add that in to the docs? or I might just change the import function to `Math.Abs()` the value.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/commit/0cdd1c3eceab1c6134c9c606801423cfa76a184a

**Comment by fsobolev** [comment]
> Maybe we should add that in to the docs?

Okay, I will add it to my list of required changes in docs for the next version.
