### ISSUE TITLE
Import from ofl, qif or csv file always give a "0 transactions imported"

### ISSUE THREAD

**Issue by Ghorin46** [nlogozzo/NickvisionMoney#265]
Hello
I tried to import data from my bank account but whatever the format I choose (qif, ofl, csv), I always get the "0 itransactions imported" message. 
I'm french and using a Linux Fedora 37 workstation with french numeric / date / time / numbers format settings.
Is there a way to get debug message that might help finding the root cause. I tried to use different localization settings in the export tool of my bank and tried to put american-like localization settings, but it didn't change anything, I still get the same result.

**Comment by nlogozzo** [comment]
The american-styled date and amount formats should work no problem. 
Granted for csv, the file must be of correct format...see #262

There won't be any error messages since the program catches them to avoid crashes. If you could send me samples of the files you are using that'd be great!

**Comment by Ghorin46** [comment]
Here is an example using OFX with format of Money 2003 or later. 
[comptes.txt](https://github.com/nlogozzo/NickvisionMoney/files/10528147/comptes.txt)

**Comment by QazCetelic** [comment]
I'm experiencing the same issues, also using Fedora 37.

**Comment by nlogozzo** [comment]
Will be fixed in #286 

NOTE: QIF files must have dates in US format. OFX files must have dates in YYYYMMDD format (as per document specifications).

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.2.0-rc1-f1
