### ISSUE TITLE
Window opens in the wrong GNOME Workspace

### ISSUE THREAD

**Issue by DaPigGuy** [nlogozzo/NickvisionMoney#281]
*Minor issue*

The window opens in the last opened workspace rather than the workspace the app entry is dragged into, and appears to be the only installed GTK app other than Tube Converter to exhibit this issue, which is interesting.

[Screencast from 2023-02-05 14-53-19.webm](https://user-images.githubusercontent.com/8540562/216850811-7d568e90-804a-4a86-87b2-1a4f98628155.webm)

**Comment by fsobolev** [comment]
Interesting... I will look if something in our code messes up something in GTK so it forces the compositor to open the window in wrong workspace.

**Comment by nlogozzo** [comment]
This could be because of the fact that the application is running in dotnet and then dotnet spawns the gtk application, causing it to just be in the focused workspace as opposed to one you dragged it too.

**Comment by nlogozzo** [comment]
There might be nothing we can do about this. Best thing to do is open Denaro and then move it to your prefered workspace after.

**Comment by nlogozzo** [comment]
Ah wait, you say Tube Converter doesn't work correctly either?

**Comment by fsobolev** [comment]
> This could be because of the fact that the application is running in dotnet and then dotnet spawns the gtk application, causing it to just be in the focused workspace as opposed to one you dragged it too.

I don't think dotnet has anything to do with GUI. It's either GTK or gir.core. And since it also happens with TubeConverter (and Tagger, I just tested), it's not gir.core. So we messed something up in how application starts.

**Comment by nlogozzo** [comment]
It's just `adw_application_new()` 🙃 the same way all other apps do it haha

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.2.0-rc1-f1
