### ISSUE TITLE
Group Change Not Applying In Transaction

### ISSUE THREAD

**Issue by mrbvrz** [nlogozzo/NickvisionMoney#306]
Group selection in this application does not work properly, the selected group is always **wrong**, does not match the one selected after saving.

Here I am using *Denaro* on **Fedora 37**

**Comment by fsobolev** [comment]
I can't reproduce it.
Could you provide an account (without sensitive information) that is affected by this bug?

**Comment by mrbvrz** [comment]
Like the picture below. I have selected the **Ditreskrimsus Complaints** group in **Transaction-9**, but after it was saved and reopened, the group that had been selected changed not according to the one previously selected.

![Screenshot from 2023-02-14 01-45-08](https://user-images.githubusercontent.com/3890123/218551068-c2922956-d700-466d-ab77-63d037bd4fde.png)
![Screenshot from 2023-02-14 01-45-37](https://user-images.githubusercontent.com/3890123/218551076-45502324-c3db-4475-89c5-d7afd2d39402.png)

**Comment by nlogozzo** [comment]
Could you provide the account file used?
Was this account file ever used with beta versions of Denaro?

**Comment by fsobolev** [comment]
@nlogozzo , I managed to reproduce, something goes wrong when there are spaces in group names

**Comment by mrbvrz** [comment]
Thank you..

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.2.1
