### ISSUE TITLE
Problem when filling description in Group Modal

### ISSUE THREAD

**Issue by mrbvrz** [nlogozzo/NickvisionMoney#308]
Problem when filling description in Group Modal
when making changes to the description it always gets thrown to the end of the sentence

OS: Windows 11

https://user-images.githubusercontent.com/3890123/219271704-62d79810-6ec2-44c1-ad43-55aa735a65d1.mp4

**Comment by nlogozzo** [comment]
Ah this is probably due to the check for `;` we have in text fields...
@fsobolev Does this happen in GNOME too or no?

**Comment by fsobolev** [comment]
> Ah this is probably due to the check for `;` we have in text fields... @fsobolev Does this happen in GNOME too or no?

no, doesn't happen in GNOME

**Comment by fsobolev** [comment]
https://github.com/nlogozzo/NickvisionMoney/blob/bda8a8d2ad581fa5fc9a3872de082f64f0dbb6ba/NickvisionMoney.WinUI/Views/GroupDialog.xaml.cs#L98

@nlogozzo I guess this causes the bug

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/commit/b19368f07fc544d097999be8fa417bf9c9f208f5

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.2.1
