### ISSUE TITLE
Missing Locales

### ISSUE THREAD

**Issue by kdw2060** [nlogozzo/NickvisionMoney#317]
Since the latest update (2023.2.0) the app crashes as soon as I try to open an account / a nmoney file.

To make sure there was no issue with my existing account file I created a new one, this also results in an application crash.
Another thing I tried was to give complete file system access through Flatseal, but that doesn´t make a difference.

The gnome problem logger doesn't offer me an immediate clue as to what might be the cause. I can look for a certain value in the crash/problem report if that's helpful.

**Comment by fsobolev** [comment]
It will be helpful if you can run the app in a terminal and provide the output.
```
flatpak run org.nickvision.money
```

**Comment by kdw2060** [comment]
When I run the command I get `(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 20:48:23.984: gtk_widget_add_css_class: assertion 'GTK_IS_WIDGET (widget)' failed` as soon as the program starts, but this doesn't crash the app.

When I try to open the account and the app crashes I get this:
```
Unhandled exception. System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'name')
nl-BE.utf8 is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at NickvisionMoney.Shared.Controllers.AccountViewController.get_CultureForNumberString() in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/AccountViewController.cs:line 180
   at NickvisionMoney.GNOME.Views.AccountView.CreateGroupRow(Group group, Nullable`1 index) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 595
   at NickvisionMoney.Shared.Controllers.AccountViewController.StartupAsync() in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/AccountViewController.cs:line 415
   at NickvisionMoney.GNOME.Views.AccountView.StartupAsync() in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 683
   at NickvisionMoney.GNOME.Views.MainWindow.AccountAdded(Object sender, EventArgs e) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/MainWindow.cs:line 384
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

So it looks like some internationalisation issue.

**Comment by nlogozzo** [comment]
Ah, could you send the values of your LC vars?
Type `locale` in terminal and send that output.

**Comment by nlogozzo** [comment]
@fsobolev If we get this error, in general, we should just default to en-US, no?
If you agree ill implement that.

**Comment by fsobolev** [comment]
> @fsobolev If we get this error, in general, we should just default to en-US, no? If you agree ill implement that.

Maybe it would make sense to first try base locale (in this case `nl-BE` -> `nl`) and then use `en-US`?

**Comment by nlogozzo** [comment]
Would it accept base cultures such as just "en"? Since this is coming from CultureForDateString it wouldn't accept it since the formating part comes from the country code (i.e. the second part of the culture..US)

**Comment by fsobolev** [comment]
> Would it accept base cultures such as just "en"? Since this is coming from CultureForDateString it wouldn't accept it since the formating part comes from the country code (i.e. the second part of the culture..US)

It uses LC_MONETARY, correct? Then I guess it's fine to use `en-US` and users will be able to override it by setting LC_MONETARY using Flatseal.

**Comment by kdw2060** [comment]
> Ah, could you send the values of your LC vars? Type `locale` in terminal and send that output.

```
LANG=nl_BE.utf8
LC_CTYPE="nl_BE.utf8"
LC_NUMERIC=nl_BE.utf8
LC_TIME=nl_BE.utf8
LC_COLLATE="nl_BE.utf8"
LC_MONETARY=nl_BE.utf8
LC_MESSAGES="nl_BE.utf8"
LC_PAPER=nl_BE.utf8
LC_NAME=nl_BE.utf8
LC_ADDRESS=nl_BE.utf8
LC_TELEPHONE=nl_BE.utf8
LC_MEASUREMENT=nl_BE.utf8
LC_IDENTIFICATION=nl_BE.utf8
LC_ALL=
```

**Comment by nlogozzo** [comment]
Ah I see the problem...its not removing the utf8..probably have to convert the string to lowercase and remove it. I think currently it removes "UTF8" and not "utf8"

**Comment by nlogozzo** [comment]
May i just ask...what distro are you using.
Usually the distro formats the locale as `en_US.UTF-8` i've never seen `.utf8`...
I'll include a fix for it anyway, but just wondering

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/commit/2a672f06e646ef54b45dc2561986508127a087c6

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.2.1

**Comment by kdw2060** [comment]
> May i just ask...what distro are you using. Usually the distro formats the locale as `en_US.UTF-8` i've never seen `.utf8`... I'll include a fix for it anyway, but just wondering

Nobara, which is Fedora (36) with some tweaks

And thank you for the very quick resolution and release :heart:
