### ISSUE TITLE
Add more decimal places

### ISSUE THREAD

**Issue by mpi3d** [nlogozzo/NickvisionMoney#318]
Hi,

Is it possible to add more decimal places in amounts to support cryptocurrencies. It sounds like currently there is only 2 decimal places. So an amount of `0.001` is rounded to `0.00`. But for money like Bitcoin, `0.001 ₿` is around `20 $` so decimals are not negligible.

Thanks for your work anyway!

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.3.0-beta2

**Comment by mpi3d** [comment]
It's working thanks!
