### ISSUE TITLE
Add `Ctrl`+`N` shortcut for "New Window"

### ISSUE THREAD

**Issue by TheEvilSkeleton** [nlogozzo/NickvisionMoney#324]
Per the [GNOME HIG](https://developer.gnome.org/hig/reference/keyboard.html), the New Window button from the primary menu should have the `Ctrl`+`N` shortcut assigned. 
![image](https://user-images.githubusercontent.com/50847364/220818538-f268e29a-9e9c-49d6-9cc7-48f62c6cc281.png)

**Comment by nlogozzo** [comment]
@fsobolev @DaPigGuy if one of you want to implement this for #322 ... as well as #321

**Comment by TheEvilSkeleton** [comment]
Now that I think of it, this shortcut makes sense for creating a new account too. After carefully reading the HIG:

> Creates a new content item, **sometimes** in a new window or tab.

If I understand correctly, creating a new window is second resort?

**Comment by nlogozzo** [comment]
> Now that I think of it, this shortcut makes sense for creating a new account too. After carefully reading the HIG:
> 
> > Creates a new content item, **sometimes** in a new window or tab.
> 
> If I understand correctly, creating a new window is second resort?

Yes. These are the current shortcuts:
![image](https://user-images.githubusercontent.com/17648453/220819142-1ae49ab2-00f8-48f0-a35a-41a9825c9513.png)

So both `Ctrl+N` and `Ctrl+N+Shift` are taken. Probably best to leave it as is.

**Comment by TheEvilSkeleton** [comment]
Yeah, I think the way it is right now is better. I think I overthought the too much. Sorry for opening the issue :/

**Comment by nlogozzo** [comment]
No worries...always good to discuss and make sure we are doing things right :)
