### ISSUE TITLE
Group colors

### ISSUE THREAD

**Issue by fsobolev** [nlogozzo/NickvisionMoney#339]
>It would be cool if i can link a color to a group. For example i want, that if i add a expese/income with the group "food" the group sets automaticly the color to... any color i set. That would be cool

Requested by programmtube:matrix.teckids.org

We could add color row to group dialog, make groups checkboxes colored, and in transaction dialog add dropdown next to color button: it will have 2 options - "use unique color" and "use group color", the default value will be set depending on a setting (in preferences, I don't think it needs to be per account) and when no group is selected it will be disabled.
In CSV, a new column can be created for group color and for RGBA "g" or something else can be used to mark that this transaction uses group color.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.4.0-rc1
