### ISSUE TITLE
Sidebar size is small for Urdu language.

### ISSUE THREAD

**Issue by ArbazIrshad** [nlogozzo/NickvisionMoney#344]
I am using Fedora 37 and have set the format in Region and Language in setting to my country (Pakistan). This converts the app calendar to Urdu. The calendar is not able to fit in the sidebar. So, the sidebar becomes horizontally scrollable, which ruins the user experience of the app as it hides the income and expense. You have to scroll horizontally to view the info. Also, I can't adjust the size of the sidebar by dragging on the border.

**Comment by DaPigGuy** [comment]
This can probably be addressed in the Blueprints port when the account view is ported over :)

**Comment by fsobolev** [comment]
> This can probably be addressed in the Blueprints port (#345) when the account view is ported over :)

I can't find a way to force scrolled window to autoresize using properties. We will need to do something from code, probably like this:
```
_scrolledWindow.GetHadjustment().OnNotify += (sender, e) =>
{
    if (e.Props.GetName() == "upper")
    {
        _scrolledWindow.SetMinContentWidth(_contentBox.GetAllocatedWidth());
    }
};
```

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.3.0-beta1

**Comment by ArbazIrshad** [comment]
I just tested it and the new beta fixes the issue. Thank you :)
