### ISSUE TITLE
Automatically convert numpad's . to a whatever symbol separates integers and decimals in the locale

### ISSUE THREAD

**Issue by bordam** [nlogozzo/NickvisionMoney#35]
> A good thing would be to automatically convert numpad's . to a whatever symbol separates integers and decimals (e.g. comma), like gnumeric does.

_Originally posted by @bordam in https://github.com/nlogozzo/NickvisionMoney/issues/11#issuecomment-1312789887_

**Comment by nlogozzo** [comment]
Should be fixed with https://github.com/nlogozzo/NickvisionMoney/commit/2f4cc4e743e78eca3c10622266ee22a63da438d1

**Comment by nlogozzo** [comment]
Please keep in mind that if your keyboard locale is `en`, then that gets interpreted as `.` for the decimal separator. If your keyboard locale, for your case, is in `it`, then it should input as `,`.

**Comment by bordam** [comment]
Hmm, it only works on xorg for me and when I write a . the blinking cursor goes back to the beginning of the amount...

**Comment by nlogozzo** [comment]
The fact that it only works on xorg is out of my control. Must be an issue with wayland and gdk events. 

However, i will fix it so the cursor stays at the end.

**Comment by nlogozzo** [comment]
> Gnumeric manages to do it just fine... is it a gtk4 issue at this point? I think we should report it, in that case

Yes I believe it night be a gtk4 issue, which seems to happen a lot on Wayland...

**Comment by fsobolev** [comment]
> Please keep in mind that if your keyboard locale is `en`, then that gets interpreted as `.` for the decimal separator. If your keyboard locale, for your case, is in `it`, then it should input as `,`.

Yesterday I tested this on a PC with AMD videocard using radeon driver (idk if it does matter, but just in case) and Wayland. Now I tested on another PC with NVIDIA card and proprietary driver. On Wayland, works as expected. On Xorg, if I run the app with `en` locale it works as expected, but with `ru` locale it always inputs `,` for both `en` and `ru` keyboard layout, but if the layout is `en`, the cursor goes to the beginning of a line.

**Comment by nlogozzo** [comment]
@bordam The position of the cursor should be fixed in the latest commit: https://github.com/nlogozzo/NickvisionMoney/commit/9b54008665c2b420733a024cc80a7a115537a6e8

**Comment by bordam** [comment]
Bad news, with the latest commit a crash occours to desktop whenever I type . in xorg

[Video del 2022-11-23 17-35-13.webm](https://user-images.githubusercontent.com/95233098/203600770-ca750ff5-bef9-4bdb-b6fa-a51347e6a4d4.webm)

**Comment by nlogozzo** [comment]
And if the application still crashes, would you be able to run it from the terminal and provide me with any error messages you get when it crashes.

**Comment by bordam** [comment]
![immagine](https://user-images.githubusercontent.com/95233098/203606615-2f2e6442-fe93-4b4c-9926-785b2f457e53.png)

**Comment by nlogozzo** [comment]
[Screencast from 2022-11-23 12-27-50.webm](https://user-images.githubusercontent.com/17648453/203611167-61374723-90fc-4bfc-844c-7c4221e0cfa3.webm)

I'm on xorg with NVIDIA drivers and it works no problem for me...

**Comment by nlogozzo** [comment]
what happens if you go on wayland?

**Comment by bordam** [comment]
Nothing: . is not converted and no CTD occurs

**Comment by nlogozzo** [comment]
I guess it is best if I remove this feature from the release until we can get it working correctly for you.

**Comment by bordam** [comment]
This feature works on both x and wayland for gnome calculator (gtk4+libadwaita)
Maybe we can borrow some code from it?

**Comment by nlogozzo** [comment]
I will look at how gnome calculator handles it.
Is your keyboard locale set for it_IT? I know for @fsobolev it automatically changes to `,` when his keyboard layout is in his locale and uses `.` when in en_US, which is to be expected.

**Comment by bordam** [comment]
Sorry for late answer!!

Keyboard layout is Italian indeed. LC_ALL is it_IT.utf8 and localectl status outputs it as keyboard and x11 layouts.

I have an AMD GPU.

**Comment by nlogozzo** [comment]
@fsobolev Any idea what to do with this?
You say this is already working correctly when you switch the keyboard layout to `ru_RU` for you, correct? When you type numpad `.` you get `,`?

**Comment by nlogozzo** [comment]
@bordam Is this still an issue for you in the new `Denaro` version?

**Comment by fsobolev** [comment]
@nlogozzo maybe this will work differently in C#... I mean, maybe there will be no crash and the feature will work correctly even if it will be implemented the same way it was in C++ version. We can try.

**Comment by bordam** [comment]
Yes, it’s still an issue for me.

**Comment by nlogozzo** [comment]
@bordam Does this work correctly in gnome calculator?

**Comment by bordam** [comment]
Yes, it works correctly and it almost seems like it’s not “converting” the character, but it’s rather automatically inserting the correct one

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.2.0-rc1-f1
