### ISSUE TITLE
Bug when inserting values when the Amount field is selected

### ISSUE THREAD

**Issue by cassiogomes00** [nlogozzo/NickvisionMoney#357]
## Description

When you select the value in the Amount field and enter new numbers, the value remains in the selected state, causing the new numbers to replace the previous ones. This behavior is intermittent, but not uncommon.

## How To Reproduce

- Open an account;
- Open the dialog to create or edit an transaction;
- Select the value in the Amount field;
- Type any sequence of numbers.

## Expected behavior

When you enter the first number, the value in the field is no longer selected and the next numbers are added after the numbers already entered.

## Video

[Screencast from 2023-03-10 21-54-54.webm](https://user-images.githubusercontent.com/43018520/224455517-20b63c6c-6202-44d6-87df-ccb058f54bcc.webm)

## System info

- App version: 2023.2.2
- Packaging: Flatpak

**Comment by fsobolev** [comment]
Can you reproduce this bug:
1. with entries other than transaction amount or transfer amount?
2. with "Insert decimal separator" set to "Off" in settings?

If for any of 2 questions the answer is yes, it's either GTK or libadwaita bug and we can't do anything about this.
I can't reproduce this bug at all.
