### ISSUE TITLE
Localize date format

### ISSUE THREAD

**Issue by bordam** [nlogozzo/NickvisionMoney#36]
Money should show dates in the local format. Opening this issue since #11 was closed

> Same problem also applies to dates!!

_Originally posted by @bordam in https://github.com/nlogozzo/NickvisionMoney/issues/11#issuecomment-1306203842_

**Comment by nlogozzo** [comment]
Should be fixed with the latest commit: https://github.com/nlogozzo/NickvisionMoney/commit/854f5f053688810bcb0fea92d1ac0a24f00cfaaa
