### ISSUE TITLE
Change rows width in generated PDF

### ISSUE THREAD

**Issue by fsobolev** [nlogozzo/NickvisionMoney#360]
Not sure about other rows, but at least Id row should be changed to fit translations that contain more than 3 characters.

![](https://user-images.githubusercontent.com/117388856/224529654-6e317791-abf0-4d70-b8ce-707189d76fbf.png)

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.3.0-beta2
