### ISSUE TITLE
QIF import broken

### ISSUE THREAD

**Issue by ascpial** [nlogozzo/NickvisionMoney#368]
I tried to import data from an other app, HomeBank, as well as the example file given in #265 and the toaster says "0 transactions imported".

The format of the date in both files is correct (US date: MM/DD/YYYY).

I'm using the latest version at the time of writing, which is [`2023.2.2`](https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.2.2).

A QIF file that is broken: [test.zip](https://github.com/nlogozzo/NickvisionMoney/files/10970843/test.zip)

**Comment by nlogozzo** [comment]
https://user-images.githubusercontent.com/17648453/225073475-4231c96d-fc74-4e01-9d69-18e3121e9e61.mp4

I can't reproduce it...works fine for me.

**Comment by nlogozzo** [comment]
^ That's running [V2023.3.0-beta1](https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.3.0-beta1), but that release did not change QIF from the latest stable.

**Comment by ascpial** [comment]
Sorry but everything is in french:

[Capture vidéo du 2023-03-14 17-46-34.webm](https://user-images.githubusercontent.com/72463129/225077496-fb918423-e9fa-43a7-925a-fa2efc506def.webm)

There is nothing in the list after restarting.

**Comment by nlogozzo** [comment]
It worked fine for me using GNOME version too. 
Maybe it's because the application is in French. 
If you run the app using `en-US` does it work?

**Comment by ascpial** [comment]
I tried in english, and it works fine, so the issue might come from language translation.

**Comment by nlogozzo** [comment]
I have to see what localization occurs for QIF...and i'll fix it.

**Comment by nlogozzo** [comment]
I believe this line is the problem: https://github.com/nlogozzo/NickvisionMoney/blob/main/NickvisionMoney.Shared/Models/Account.cs#L1354

I believe the `en_US` culture needs to be passed to that DateTime function other wise it will try to parse the date with the current locale instead of en_US.

I'm not home right now so I can't make the change and test. Maybe @fsobolev can.

**Comment by fsobolev** [comment]
> I'm not home right now so I can't make the change and test. Maybe @fsobolev can.

I will work on it.

**Comment by ascpial** [comment]
I quickly tested the fix with the CI build, thanks you for the support!

**Comment by nlogozzo** [comment]
Once #355 is merged, I'll release beta 2 with all the file fixes :)

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.3.0-beta2

**Comment by kivutar** [comment]
Using 2023.4.1 from flathub I'm also having issues importing a QIF with date format DD/MM/YYYY.

If I change the dates in the QIF, Denaro is able to import the file properly.

**Comment by nlogozzo** [comment]
@kivutar As per docs: https://htmlpreview.github.io/?https://raw.githubusercontent.com/NickvisionApps/Denaro/2023.4.1/NickvisionMoney.Shared/Docs/html/C/import-export.html

>  Quicken Interchange Format (.qif)
Dates should be in English (US) format (MM/DD/YYYY).
