### ISSUE TITLE
Night greeting contains morning string

### ISSUE THREAD

**Issue by flipflop97** [nlogozzo/NickvisionMoney#373]
The night greeting contains the string "Good Morning!", while it should be "Good Night!".

https://github.com/nlogozzo/NickvisionMoney/blob/30e32ad4bebb9d7e565fb30dc7cee4e795ac68f3/NickvisionMoney.Shared/Resources/Strings.resx#L224-L228

**Comment by nlogozzo** [comment]
In en-US, good night is an incorrect greeting. Between the hours of 00-06 the correct greeting is good morning in english.  Hence why the comment says not to translate literally.  If your culture says good night instead for those hours, please translate it as good night instead of good morning.
