### ISSUE TITLE
[UI/UX] Improve start screen

### ISSUE THREAD

**Issue by fsobolev** [nlogozzo/NickvisionMoney#38]
**The problem**:

Account menu duplicates functionality of start screen (both have buttons to open account or create a new one). If it's the first time a user starts the app, account menu becomes completely pointless, because the list of recent files is empty.

**The idea**:

* If the list of recent files is not empty, show it on the start screen. This will make opening a recent file faster after the app starts.
* Hide account menu button until an account is opened. This way there will be no duplicated functionality and a user will never see an empty list of recent files.

**Comment by nlogozzo** [comment]
I like the ideas you mentioned. This is Builder's start screen:
![image](https://user-images.githubusercontent.com/17648453/201723152-e8379a2e-f8bc-4e7b-8ae8-18d2297a05e1.png)
Maybe something like this?

**Comment by nlogozzo** [comment]
Would you be able to create some mockups and we can play around with the design?

**Comment by fsobolev** [comment]
![](https://i.imgur.com/699ZJwL.png)
![](https://i.imgur.com/5Crxe1p.png)

**Comment by nlogozzo** [comment]
Wow! This looks really good!
I think the second option is the best especially for large resolutions.

**Comment by nlogozzo** [comment]
Did you create this with blueprint or xml? Could you paste that code here? Or create a PR implementing it yourself if your up for it :)

**Comment by nlogozzo** [comment]
Money also supports dragging a `.nmoney` file from a file manager into the app to open it. Could you maybe add a label underneath the buttons that says something like: "You may also drag in a file from your file browser to open."

**Comment by fsobolev** [comment]
I found it hard to create mockups in Calambache, and Glade doesn't seem to support Adwaita yet. So I wrote it in python 🐍 And since I actually have the code, I will just rewrite it in C++ and send you a PR :)

> Could you maybe add a label underneath the buttons that says something like: "You may also drag in a file from your file browser to open."

Sure, no problem :+1:

**Comment by nlogozzo** [comment]
There is an app known as [Workbench](https://flathub.org/apps/details/re.sonny.Workbench) that allows for creating Gtk4/Libadwaita mockups in XML or Blueprint. It's a pretty nice tool

**Comment by nlogozzo** [comment]
> I found it hard to create mockups in Calambache, and Glade doesn't seem to support Adwaita yet. So I wrote it in python snake And since I actually have the code, I will just rewrite it in C++ and send you a PR :)

If you have any questions with C++ or any implementation details, you know where to reach me!

**Comment by zothma** [comment]
@fsobolev, I love the idea of giving access to recent right from the beginning, but I personally feel like it feels a bit empty now, wouldn't it be better to add some kind of title before, or something? Maybe also enlarge the ListBox would be better? For the moment, let's keep in mind we have a maximum of three recent files so the ListBox won't grow at all.
By the way, do you plan on deleting the actual account menu?

**Comment by nlogozzo** [comment]
> By the way, do you plan on deleting the actual account menu?

The account menu will stay but instead it will only be displayed when an account is open, since the start screen disappears with an account open.

**Comment by fsobolev** [comment]
Closing since #40 was merged 🎉
