### ISSUE TITLE
Cannot see folders and files names in denaro file manager

### ISSUE THREAD

**Issue by gmonacho** [nlogozzo/NickvisionMoney#388]
![image](https://user-images.githubusercontent.com/42712988/226142690-8a4872cf-1b80-4c41-b3b5-817a2e150bd6.png)
![image](https://user-images.githubusercontent.com/42712988/226142737-6c803281-47cc-4623-8e4e-18d32c59296a.png)
I can browse into folders and select a file, but the text is not displayed

**Comment by fsobolev** [comment]
This was fixed in the latest beta
