### ISSUE TITLE
App Crashed after adding new transaction

### ISSUE THREAD

**Issue by Krindog7337** [nlogozzo/NickvisionMoney#401]
Sometimes when i want to add new transaction the app is not responding and crashed. I've tried to run it from terminal and it showed this log before crashed

`malloc(): unaligned tcache chunk detected`

**Comment by nlogozzo** [comment]
When you re-open the app is the new transactions there in the account or no?

**Comment by Krindog7337** [comment]
the transaction is added, but it's very annoying when i want to add more transaction and it keeps crashing oftenly

**Comment by nlogozzo** [comment]
Are you adding a receipt to the transaction?

If you make a new account and add transactions to it, does the application still crash?

Are there any other errors/output before the line: `malloc(): unaligned tcache chunk detected`?

`malloc` is a C-error so it could be GTK or sqlite.

**Comment by fsobolev** [comment]
> `malloc` is a C-error so it could be GTK or sqlite.

And since we have the same error in TC randomly happening on validation, I guess it's probably GTK... 😕

**Comment by Krindog7337** [comment]
> Are you adding a receipt to the transaction?
Well some of my transactions have receipt, but either adding new transaction with receipt or not it still crash the app

> If you make a new account and add transactions to it, does the application still crash?
Fresh new account don't crash, but as soon as i imported all transactions from previous account it's started to crash again

> Are there any other errors/output before the line: `malloc(): unaligned tcache chunk detected`?
No any error before that, only gtk-warning that i believe it's my theme error

**Comment by Krindog7337** [comment]
another error i got when trying to add new transaction

`**
Gtk:ERROR:../gtk/gtkcssnode.c:321:lookup_in_global_parent_cache: assertion failed: (node->cache == NULL)`

`double free or corruption (fasttop)`

`free(): double free detected in tcache 2`

and sometimes it shows no error message at all

**Comment by fsobolev** [comment]
@nlogozzo maybe it's some threading issue? https://stackoverflow.com/questions/67146064/gtk-crashes-on-adding-and-removing-listboxrows

**Comment by nlogozzo** [comment]
Could be...but the fact that it doesn't crash with a new account and only with the only account data makes me feel like something is misconfigured in the database of said account file.

**Comment by Krindog7337** [comment]
well here's the new account with old data

[notmyliteralwallet.zip](https://github.com/nlogozzo/NickvisionMoney/files/11084521/notmyliteralwallet.zip)

**Comment by Krindog7337** [comment]
well i create new account and some transaction (without receipt) and it's still have some crashes, but not with `malloc(): unaligned tcache chunk detected` error

here's the errors i got 
`**
Gtk:ERROR:../gtk/gtkcssnode.c:321:lookup_in_global_parent_cache: assertion failed: (node->cache == NULL)
Bail out! Gtk:ERROR:../gtk/gtkcssnode.c:321:lookup_in_global_parent_cache: assertion failed: (node->cache == NULL)
`
and some crashes without error log

**Comment by nlogozzo** [comment]
https://user-images.githubusercontent.com/17648453/228110269-858df47f-6825-4014-8dad-c64a7fe59d04.mp4

On first try on WinUI, preview although, seems to be no issues. Going to try Denaro stable and preview on Linux...

**Comment by nlogozzo** [comment]
https://user-images.githubusercontent.com/17648453/228110706-55f87828-719f-4cd9-99b1-9aeba4516eb2.mp4

No problem on Denaro stable either...can't reproduce...

**Comment by nlogozzo** [comment]
What distro and desktop env are you using? (including versions)
Flatpak, AUR, manual?
Wayland or XORG, what GPU?

**Comment by Krindog7337** [comment]
> What distro and desktop env are you using? (including versions) Flatpak, AUR, manual? Wayland or XORG, what GPU?

Distro : Fedora Linux 37 (Workstation Edition)
Desktop Env : Gnome 43.1 on Wayland
GPU : Mesa Intel® HD Graphics 2000 (SNB GT1)

**Comment by Krindog7337** [comment]
> No problem on Denaro stable either...can't reproduce...

well the issue exist randomly after adding some more transactions, not just one transaction. I don't know if this only affect my device or not

**Comment by nlogozzo** [comment]
> well the issue exist randomly 

ah, well I thought you couldn't add a transaction at all, as in it was crashing every single time. If it's occurring randomly then it's probably related to what @fsobolev said, similar to what is happening with TC.

**Comment by nlogozzo** [comment]
> https://stackoverflow.com/questions/67146064/gtk-crashes-on-adding-and-removing-listboxrows

this could very likely be it. we have to make sure we are removing rows from GTK thread, no async, nothing like that. Might have to wrap everything in g_idle_add() so it gets called from main context.

**Comment by nlogozzo** [comment]
@Krindog7337 Can you download this artifact and install the flatpak package with a potential fix...and let me know how it goes :)
### Download
https://github.com/nlogozzo/NickvisionMoney/actions/runs/4549018685
### Install
- Extract the `org.nickvision.money.flatpak` file
- Run `flatpak install org.nickvision.money.flatpak` from the directory containing the .flatpak file
- Run `flatpak run org.nickvision.money//master` to start the app!

**Comment by nlogozzo** [comment]
^ Scratch that...it's probably not going to work well

**Comment by Krindog7337** [comment]
> https://github.com/nlogozzo/NickvisionMoney/actions/runs/4549018685

It works now, no crash happened :smile:

**Comment by nlogozzo** [comment]
> > https://github.com/nlogozzo/NickvisionMoney/actions/runs/4549018685
> 
> It works now, no crash happened 😄

oh actually...haha, ok!

**Comment by nlogozzo** [comment]
Could you try this artifact as well: https://github.com/nlogozzo/NickvisionMoney/actions/runs/4555079032

The previous artifact froze the UI when updating rows instead of showing the spinner. This artifact should fix that ^. Let me know how it goes :)

**Comment by Krindog7337** [comment]
> Could you try this artifact as well: https://github.com/nlogozzo/NickvisionMoney/actions/runs/4555079032

well, the app is crash more often with this artifact :disappointed: 
error log :
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at NickvisionMoney.GNOME.Controls.TransactionRow.Show() in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Controls/TransactionRow.cs:line 126
   at NickvisionMoney.Shared.Controllers.AccountViewController.FilterUIUpdate() in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/AccountViewController.cs:line 1047
   at NickvisionMoney.Shared.Controllers.AccountViewController.AddTransactionAsync(Transaction transaction) in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/AccountViewController.cs:line 642
   at NickvisionMoney.GNOME.Views.AccountView.<>c__DisplayClass86_0.<<NewTransaction>b__1>d.MoveNext() in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 742
--- End of stack trace from previous location ---
   at NickvisionMoney.GNOME.Views.AccountView.<>c__DisplayClass86_0.<<NewTransaction>b__0>d.MoveNext() in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 742
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by nlogozzo** [comment]
Ok new artifact for you! Try this one: https://github.com/nlogozzo/NickvisionMoney/actions/runs/4570301022 :)

**Comment by Krindog7337** [comment]
> Try this one: https://github.com/nlogozzo/NickvisionMoney/actions/runs/4571198859 :)

still got some crashes, but this one not even reported any error message

**Comment by fsobolev** [comment]
> still got some crashes, but this one not even reported any error message

Uhhhh... We were sure it's fixed now >_<
Sorry for consistently asking you to test changes, but neither Nick nor I can reproduce the issue (although I can reproduce the same issue in Tube Converter). The problem is with threads: GTK requires every call that changes something in the UI to be executed on a thread where GTK started, otherwise there is a chance it will randomly crash (either silently or with `malloc` or `free` error). It is not handled automatically, so we have to ensure that all needed parts of code are executed on the GTK thread. And we thought we did this... But turns out we missed something 😕 
In the one artifact that wasn't crashing absolutely everything was running in a single thread - but it's not a solution because this will cause the app freeze during long operations (like updating a transaction with dozens of repeats for example).

> and some question, is this error message below related to this bug??

Most likely not. Even tho these messages say "critical", they don't indicate that something fatal is happening.

**Comment by fsobolev** [comment]
Could you try this please? https://github.com/nlogozzo/NickvisionMoney/actions/runs/4578495817

**Comment by Krindog7337** [comment]
> Could you try this please? https://github.com/nlogozzo/NickvisionMoney/actions/runs/4578495817

Glad no crash happened :smiley: :]

**Comment by nlogozzo** [comment]
Finally 🎉

**Comment by fsobolev** [comment]
@Krindog7337 Could you please try [this](https://github.com/nlogozzo/NickvisionMoney/actions/runs/4591686266) and check if the app crashes on adding a new group?

**Comment by Krindog7337** [comment]
> @Krindog7337 Could you please try [this](https://github.com/nlogozzo/NickvisionMoney/actions/runs/4591686266) and check if the app crashes on adding a new group?

Adding a new group : no crashes
Adding new transaction: no crashes

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.4.0-beta1
