### ISSUE TITLE
Changing sorting order causes transactions in the list to mess up

### ISSUE THREAD

**Issue by fsobolev** [nlogozzo/NickvisionMoney#408]
Steps to reproduce:
1. Add a new group and a new simple transaction with that group
2. Filter out all other groups so you will see only that new transaction
3. Change sorting order - all other transactions will appear

Or

1. Select some day in calendar (not today) that has a transaction
2. Change sorting order - there will be still "1 Transaction" in the label on top, but the transaction will disappear from the list

Happens both on stable and master.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.4.0-beta1
