### ISSUE TITLE
App not showing on app-switcher (alt+tab)

### ISSUE THREAD

**Issue by Krindog7337** [nlogozzo/NickvisionMoney#411]
when the app is opened, the app is not showing on tab switcher when it's still on loading state (top-left loading animation)

[Screencast from 2023-03-30 19-02-20.webm](https://user-images.githubusercontent.com/92032579/228818829-1db20ef2-35b5-44f7-8d08-76488848e786.webm)

**Comment by fsobolev** [comment]
This a GTK bug that affects a lot of apps, not only Denaro. I will later find the issue on GNOME Gitlab, but as far as I remember it should be fixed in GTK 4.10, and so for Denaro it will be fixed in #398
