### ISSUE TITLE
[Bug] Re-creating opened account causes file deletion

### ISSUE THREAD

**Issue by fsobolev** [nlogozzo/NickvisionMoney#42]
1. Open any account file
2. Don't close it, open account menu, start new account creation
3. Select the file of opened account, agree for it to be overwritten

Result: the account is still opened in the app window and not cleared. The file is deleted and not re-created. If you try to modify a transaction or a group, the app will crash.

**Comment by nlogozzo** [comment]
Should be fixed in https://github.com/nlogozzo/NickvisionMoney/commit/1338b4ba8719d15b6dc48d4b94abc21702e8ac15

**Comment by nlogozzo** [comment]
@fsobolev Can you confirm that this was fixed?

**Comment by fsobolev** [comment]
I confirm, it's fixed.
