### ISSUE TITLE
Add a "Notes" Field to Transaction

### ISSUE THREAD

**Issue by nlogozzo** [nlogozzo/NickvisionMoney#428]
The `Extra` field will serve as a text box that will also users to put any extra information/notes they may want to associate with a transaction

**Comment by fsobolev** [comment]
I think we can replace "Receipt" row with "Extras" row that will open another view with "Receipt" and "Note". And since there will be a lot of space we can:
1. Make "Note" field multi-line
2. Add receipt preview

**Comment by nlogozzo** [comment]
> I think we can replace "Receipt" row with "Extras" row that will open another view with "Receipt" and "Note". And since there will be a lot of space we can:

Sounds good to me :)

**Comment by nlogozzo** [comment]
Maybe this separate section we can put in its own page similar to how we have separate pages in the AccountSettingsDialog to save vertical space.

**Comment by fsobolev** [comment]
> Maybe this separate section we can put in its own page similar to how we have separate pages in the AccountSettingsDialog to save vertical space.

Yes, that's what I meant by "another view".

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.4.1-beta1
