### ISSUE TITLE
Plural forms

### ISSUE THREAD

**Issue by milotype** [nlogozzo/NickvisionMoney#48]
@nlogozzo If possible please use plural forms in strings where counts appear. Several languages need more than one plural form. IMO the plural form should be used, even if a singular form of the string will never get used.

Example **without** plular forms wich is currently used:
```
#: src/controllers/accountviewcontroller.cpp:78
#, c-format
msgid "Imported %d transactions from CSV."
msgstr "Uvezene transakcije iz CSV datoteke: %d."

```
Example **with** plular forms (for Croatian):
```
#: src/controllers/accountviewcontroller.cpp:78
#, c-format
msgid "Imported %d transaction from CSV."
msgid_plural "Imported %d transactions from CSV."
msgstr[0] "Uvezena je %d transakcija iz CSV datoteke"
msgstr[1] "Uvezene su %d transakcije iz CSV datoteke"
msgstr[2] "Uvezeno je %d transakcija iz CSV datoteke"
```

I'm not a programmer, so I don't know if `c-format` or `python-format` have to be used …

**Comment by nlogozzo** [comment]
@zothma
