### ISSUE TITLE
Password-Protect Account

### ISSUE THREAD

**Issue by nlogozzo** [nlogozzo/NickvisionMoney#59]
Add the ability to add a password to protect an account file

**Comment by brunnogama** [comment]
+1 for that.
Could be nice a PIN or something like that when we open the app.

**Comment by bordam** [comment]
> Add the ability to add a password to protect an account file

Exactly, if the password was used to encrypt the account file we could safely use services like Dropbox to sync the encrypted account file

**Comment by fsobolev** [comment]
On UI part, I think password entry could be added to the account settings dialog (but setting the password will require additional confirmation ofc).

**Comment by darkdragon-001** [comment]
> if the password was used to encrypt the account file

If going for this approach, one should not use the PIN/password directly but instead derive a more secure key using [key derivation functions](https://en.m.wikipedia.org/wiki/Key_derivation_function#Key_stretching_and_key_strengthening).

**Comment by nlogozzo** [comment]
The problem with password-protected documents is that yes the password will be encrypted in the database, but when the user types said password in a textbox (on both WinUI and GNOME) it will be stored in memory as plain text...until the password screen is cleared of course.

Now this is obviously hard, but there could be a sophisticated virus scanning memory and could see the password. 

So again, the only way the password will be stolen is if an attacker has access to the internals of your memory, but the file and the password of the file remain encrypted so they will have no access to the password via the `.nmoney` file. Only if they had access to your memory at the time of you typing in the password, otherwise it's impossible to get the password.

But, this is a risk we will have to just accept if we want to implement this feature.

**Comment by darkdragon-001** [comment]
@nlogozzo In order to build a secure app, it is essential to define the threat vector which one protects against and where the protection fails.

In your described scenario where the attacker has complete access over the memory and also has knowledge on how to interpret the 0s and 1s in the memory, he will also have access over the decrypted parts of the database which is displayed to the user as part of the UI. I don't see a way around it and honestly in that scenario one usually has other more severe problems.

I still see huge benefits with this approach as it protects against an attacker accessing your file system or an attacker which gains access to your cloud provider where you store your (encrypted) .nmoney file.

**Comment by nlogozzo** [comment]
> Often one decrypts a file with a strong generated symmetric key and encrypts that key with a password derived key. This way, one doesn't need to rewrite the whole database on a password change and can also allow multiple passwords as a fallback to not lockout yourself. It is also possible to encrypt this symmetric key using hardware tokens like smart cards or YubiKey or similar. This way, even reading the password from memory is not enough as one also needs access to the hardware token.

Well, SQLite is very limited when it comes to passwords and encryption. It is possible thanks to [SQLChiper](https://www.zetetic.net/sqlcipher/)...but it would only support one password per file at a time. Ofc that password can be changed with knowledge of the original password.

This is how it would be implemented through the SQLite library we are using: https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite/encryption?tabs=netcore-cli

**Comment by nlogozzo** [comment]
@fsobolev The password settings will obviously be placed in `AccountSettingsDialog` where:
- The user can add a password at any time
- The user can remove and change a password if one is set
    - Removing a password while ask for confirmation through a message box

There will only be buttons in `AccountSettingsDialog` for managing password. Getting a password will come from the `PasswordDialog` control that will have `Current Password`, `New Password`, and `Confirm New Password` fields.
- `Current Password` will be grayed out when adding a password for the first time
![image](https://user-images.githubusercontent.com/17648453/213354695-e0cc437b-943d-4386-88a5-af68164785f7.png)


If you could create some mockups for placement of the buttons in `AccountSettingsDialog` and `PasswordDialog`, that'd be great :)

**Comment by fsobolev** [comment]
I want to do password dialog a bit differently, I will create mockups

**Comment by fsobolev** [comment]
| Account Settings Dialog | Password Prompt Dialog | Password Settings Dialog |
|---|---|---|
| ![](https://i.imgur.com/REijJAp.png) | ![](https://i.imgur.com/8NE2P2B.png) | ![](https://i.imgur.com/fGKnTAj.png) |

- Opening a password-protected account will create **Password Prompt Dialog** before loading an account. This dialog uses [`Adw.PasswordEntryRow`](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/class.PasswordEntryRow.html).
    > It does not show its contents in clear text, does not allow to copy it to the clipboard, and shows a warning when Caps Lock is engaged. If the underlying platform allows it, AdwPasswordEntryRow will also place the text in a non-pageable memory area, to avoid it being written out to disk by the operating system.
    > It offer a way to reveal the contents in clear text.

- **Account Settings Dialog** now contains "Set Password" row. Clicking on it will open **Password Prompt Dialog** if a password is already set to confirm that the person who wants to change the password is the same who opened the account, and then **Password Settings Dialog** will be opened.
- **Password Settings Dialog** uses `Adw.PasswordEntryRow`s too. The "Remove" button will only be visible if a password is already set. The "OK" button will only be active if both entries contain the same value. Warning message should probably be rephrased, I just wrote a short example. Pressing "Cancel" will open **Account Settings Dialog**. Pressing "Remove" or "OK" will close the dialog and show toast notification in account view with the message containing either "The password was removed" or "New password was set" respectively.

**Comment by nlogozzo** [comment]
Work on this feature can be seen here: https://github.com/nlogozzo/NickvisionMoney/pull/272

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.2.0-rc1-f1
