### ISSUE TITLE
Implement transfer between accounts

### ISSUE THREAD

**Issue by heymisphere** [nlogozzo/NickvisionMoney#6]
We could have a transfer feature, so that we can make a transfer transaction, that is that it would be shown as 'income' transaction in one account, and 'expense' in another. This can be particularly useful in cases when a single person have multiple bank accounts, or we have different use cases for different accounts but we need to transfer between them.

**Comment by nlogozzo** [comment]
Nice idea! Will definitely look to implement it.

**Comment by nlogozzo** [comment]
Should be fully implemented with: https://github.com/nlogozzo/NickvisionMoney/commit/0e114ef6b5578b23e32ba5e4d794e3f43e3e1aee

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/203698377-2f912fb0-4e56-4927-8309-7dd87fb78754.png)
![image](https://user-images.githubusercontent.com/17648453/203698306-66ec2d7d-019f-40cf-b279-52d26d690867.png)
![image](https://user-images.githubusercontent.com/17648453/203698318-c738fe8b-afa6-43b3-ba6c-0fda0a26a24e.png)

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2022.11.1-rc1
