### ISSUE TITLE
[UI/UX] Account View Redesign

### ISSUE THREAD

**Issue by fsobolev** [nlogozzo/NickvisionMoney#60]
This is a mockup for new Account View. It's not fully finished: I didn't find a way to make grid adaptive and didn't implement all the logic to make new features work. Yet. So I can't show how it will look with different window sizes, but at least you can now see how it looks by default and so we can start conversation to improve it :blush:

New features:
* Adaptive design: left pane will hide when the window is too narrow (like in Nautilus or Amberol), and the grid of transactions will change its number of columns depending on the width;
* Filter by income/expense;
* Filter by groups;
* Filter by dates;
* Transactions have icons: a user will select an icon from pre-defined list and its color (similar functionality can be seen in [Firefox Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) and [Paper](https://posidon.io/paper/))

Also remove button will be moved from transactions rows to transaction edit dialog.

Screenshots:

![](https://i.imgur.com/8X8hwbk.png)
![](https://i.imgur.com/ZuwmEfl.png)

Things to think about:
1. Order of button in headerbar: should it be Account Menu Button first and then Toggle Pane Button, or vice versa?
2. Should we allow user to select any color for icons or use pre-defined list that will change depending on the app theme (light/dark)? On screenshots you can see that icons have different colors depending on theme, but that's because I used pre-defined Adwaita styles using `add_css_class(...)`. Some arbitrary colors will look bad with dark or light theme.
3. Do we need to do something with calendar? It's just a `Gtk.Calendar` widget and it looks... not bad, but not "adwait-y" enough.

P.S. Just like with new Start Screen, I made this mockup using Python, but of course I will work on actually implementing it in the app as soon as we discuss the details.

**Comment by nlogozzo** [comment]
1. I think the order of the buttons in the header bar are fine.
2. Maybe instead of a whole set of icons...what if we did colored dots. Similar to how transaction 1 has a yellow dot, what if we just allowed the user to chose the color of the dot (kind of like how tags in a file manager work)
3. Try adding the `card` css class to the calendar widget (that's usually what I do when a widget doesn't look adwaita-y enough)

**Comment by nlogozzo** [comment]
But I love this design! I want to stay up all night to implement this now haha

**Comment by nlogozzo** [comment]
@zothma

**Comment by fsobolev** [comment]
> 2. Maybe instead of a whole set of icons...what if we did colored dots. Similar to how transaction 1 has a yellow dot, what if we just allowed the user to chose the color of the dot (kind of like how tags in a file manager work)

The question is basically the same: should it be a list of colored dots in edit transaction dialog and a user chooses one, or `Gtk.ColorChooser` will be used?

> Try adding the card css class to the calendar widget (that's usually what I do when a widget doesn't look adwaita-y enough)

Yay, that worked! Thanks!

![](https://i.imgur.com/VfMPdrH.png)

**Comment by nlogozzo** [comment]
> The question is basically the same: should it be a list of colored dots in edit transaction dialog and a user chooses one, or Gtk.ColorChooser will be used?

Probably Gtk.ColorChooser is the best option.

**Comment by nlogozzo** [comment]
Also keep in mind that Money is built in a tab interface. Each account having their own tab. So make sure it still looks ok with that and not to squeezed together i guess.

**Comment by zothma** [comment]
I love this new design ! It looks definitely better than the current one, more professional.

About the date, I don't think a whole calendar would be useful, we rather filter by month than by day, so you could use two comboboxes maybe?

**Comment by zothma** [comment]
> Also keep in mind that Money is built in a tab interface. Each account having their own tab. So make sure it still looks ok with that and not to squeezed together i guess.

Maybe this whole redesign would be time to think about another way? Keeping in mind that one of your future feature will be to allow transfer between accounts, a tabbed version may not be the best way

**Comment by fsobolev** [comment]
> About the date, I don't think a whole calendar would be useful, we rather filter by month than by day, so you could use two comboboxes maybe?

With calendar it's possible to select multiple days, thus allowing more precise filtering than just selecting a range between two dates using comboboxes.

**Comment by fsobolev** [comment]
> Also keep in mind that Money is built in a tab interface. Each account having their own tab. So make sure it still looks ok with that and not to squeezed together i guess.

![](https://i.imgur.com/2YuBYRL.png)

**Comment by fsobolev** [comment]
@nlogozzo @zothma How about we use circular buttons with ID label inside of it, instead of icons/dots? Setting small font size make it look fine even with 4-digits IDs.

![](https://i.imgur.com/5ONHU91.png)

**Comment by nlogozzo** [comment]
I think that's better. And maybe we can allow the user to change the color of that circle.

**Comment by fsobolev** [comment]
> And maybe we can allow the user to change the color of that circle.

Hm, we could allow to change a color of a circle... But I suggest that the chosen color will be the color of a label. Because this will be easier to implement and Adwaita will handle recoloring of a circle (for example, for a pure black text #000000 the circle will be light grey).

**Comment by fsobolev** [comment]
> About the date, I don't think a whole calendar would be useful, we rather filter by month than by day, so you could use two comboboxes maybe?

> With calendar it's possible to select multiple days, thus allowing more precise filtering than just selecting a range between two dates using comboboxes.

I was thinking about it and initially I wanted to use marks in calendar to show which days are applied to the filter. But wouldn't it be better to use marks on days that have transactions? Then we lose ability to mark days for filter in the calendar widget. So yeah, I think adding comboboxes at the bottom to select range is a good idea. And if a user clicks on a day in calendar, that range (and comboboxes values too) is changed to the selected day only.

**Comment by fsobolev** [comment]
![](https://i.imgur.com/6YeThBw.png) ![](https://i.imgur.com/wlql9h8.png)

Rows have buttons to select year, month and day from lists (using `Gtk.DropDown`). My plan is that lists are generated according to existing transactions, it will be impossible to select date earlier than chronologically first transaction, and the same for the last transaction (so there will not be a list of years from 1970 to infinity).
OR
We can remove `Gtk.Calendar` and make one button in each row. A button will open `Gtk.Calendar` in a popup to select date for either start or end of a range. However it will be harder to select only one day for filter (instead of simply selecting a day in the calendar, a user will need to open the expander row and select the same date both for the start and the end of a range).

**Comment by nlogozzo** [comment]
> Rows have buttons to select year, month and day from lists (using Gtk.DropDown). My plan is that lists are generated according to existing transactions, it will be impossible to select date earlier than chronologically first transaction, and the same for the last transaction (so there will not be a list of years from 1970 to infinity).

This sounds best to me

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/202828649-6ee84c46-d329-4c1b-a90a-768032203d86.png)

Slowly getting there :) This is implemented in the actual codebase. View the WIP here: https://github.com/fsobolev/NickvisionMoney/tree/new-account-view

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/202828872-b19803f2-d011-484d-bc9c-0ba03d408f7c.png)

Compact mode!
