### ISSUE TITLE
Inconsistent currency formatting

### ISSUE THREAD

**Issue by E-werd** [nlogozzo/NickvisionMoney#61]
I'm seeing some weirdness on the formatting of the currency in transactions.  Sometimes it will show a single decimal (e.g. $4.4 instead of $4.40) and sometimes it will show extra decimals (e.g. $32.01.00 instead of $32.01).  Modifying the transaction to reflect the correct amount does not correct the issue.

Attached are 3 examples.

![3](https://user-images.githubusercontent.com/1765057/202605411-c8d607e5-cc98-4300-9326-451766cf559a.png)
![2](https://user-images.githubusercontent.com/1765057/202605414-cd7c0ddb-d8f3-4237-a3e5-fca8337a5ddb.png)
![1](https://user-images.githubusercontent.com/1765057/202605416-c7814cd1-18f7-4515-a99e-81f19a966def.png)

**Comment by nlogozzo** [comment]
Should be fixed in the latest commit: https://github.com/nlogozzo/NickvisionMoney/commit/1789536a59d1d532bcbc73fc7c7ed65deae64a47

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/202629318-9f83497d-354e-416f-bdfb-d420c35d4f57.png)

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2022.11.1-beta1
