### ISSUE TITLE
Croatian translation screenshot

### ISSUE THREAD

**Issue by milotype** [nlogozzo/NickvisionMoney#65]
Can you please post a "Croatian" screenshot for the UI!
In Croatian and most european countries:

- The currency is placed "after" the amount. The currency should be localized: the current Croatian currency is "kn" (for kuna). This will change once Croatia implements the Euro. But even then, the currency symbol should be placed after the amount (European standard) => **130,55 kn** or **130,55 €**
- The decimal separator in Croatian (and other European languages) is a "comma". The "period" is used as a "thousands" separator
- Years and dates in the calendar are ordinal numbers in **Croatian**, so they need a period after the number

![Decimal separators, ordinals and currency](https://user-images.githubusercontent.com/43657314/202859520-b1232638-c1d2-4fba-9dca-1207e32782f4.png)

**Comment by nlogozzo** [comment]
I'm on an `en-us` system so the application is in English. This redesign is currently in development. Once the redesign is fully implemented and the translations are updated, you will see the application in Croatian when you run it.

**Comment by milotype** [comment]
@nlogozzo Great! Please also consider the dates and years as mentioned in my message (ordinal numbers).
