### ISSUE TITLE
[Feature Requst] Implement categories & filters by category

### ISSUE THREAD

**Issue by saligari** [nlogozzo/NickvisionMoney#66]
For me (and I believe for many others as well) one benefit of writing down income & expenses is you can group them by categories.

Take a look at homebank & skrooge. A transaction (whether + or - ) can be tagged with a category (like eating out, telephone bill, gas etc) so you can look up later how much & where you're spending.

For me it's the single most important feature for a programme like this to have.

Very simple & responsive design, nice work!

**Comment by nlogozzo** [comment]
The groups feature is already available in V2022.11.0 that allows you to associate transactions with groups.

We are working on a redesign (#60) for V2022.11.1 that will allow you to filter based on groups:
![image](https://user-images.githubusercontent.com/17648453/202919621-82e91d05-9513-4177-8523-f7470a8e132d.png)

**Comment by saligari** [comment]
Oops, sorry, missed that!

I suppose I don't have much to add then, great work!

**Comment by nlogozzo** [comment]
Haha no worries and thank you! Hopefully the redesign will be released by Wednesday/Thursday of this week.

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2022.11.1-beta1
