### ISSUE TITLE
Implement history of opened accounts

### ISSUE THREAD

**Issue by securearth** [nlogozzo/NickvisionMoney#7]
I am currently using this application for tracking my money, and whenever i open it, i need to open my account from its saved location everytime. It would be great if history would be implemented, so whenever you exit the application, it saves the locations of opened accounts last time app was running, and it reopens the same accounts when you start the app again, and if previously opened account does not exist (incase user deleted that): simply not open that one

**Comment by nlogozzo** [comment]
That's how my other applications work, for example Tagger remembers the last opened folder and reopens it on startup. However, I feel like this isn't good design for Money as Money is for of a document editor (similar to Writer/Text Editor) it edits multiple documents and starting them up everytime on startup seems like bad UX.

**Comment by nlogozzo** [comment]
However, I was thinking of creating a recents flyout in the account button of the headerbar:
![image](https://user-images.githubusercontent.com/17648453/199611669-ad8dc578-0c57-445f-b596-dd5d2569e2b5.png)

**Comment by securearth** [comment]
Recent flyout would also work

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2022.11.0-beta5

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/201547571-f992fd18-b855-44a9-b07d-a1337e1618da.png)
