### ISSUE TITLE
Don't use colors to exclusively delineate changes

### ISSUE THREAD

**Issue by jannuary** [nlogozzo/NickvisionMoney#73]
Money uses red-coloured text to signify expenses and green-coloured text to signify income. This is a pretty significant accessibility issue as it makes it difficult to see the difference between them with certain types of color blindness:

![image](https://user-images.githubusercontent.com/27908024/203212605-9c768173-421b-4644-b511-28e70bd8fb1c.png)
(simulated image)

Amounts should have + or - appended to them for clarity.

**Comment by nlogozzo** [comment]
![image](https://user-images.githubusercontent.com/17648453/203215968-2a263fad-da97-4d0a-98d2-7648f274237a.png)
![image](https://user-images.githubusercontent.com/17648453/203216009-d24c53be-c16c-4cef-8d6d-76286204016b.png)

**Comment by nlogozzo** [comment]
Fixed with https://github.com/nlogozzo/NickvisionMoney/commit/79f7d5a2187aa7960fb333b988959c11355d9f1d
