### ISSUE TITLE
Off-model pencil icon

### ISSUE THREAD

**Issue by jannuary** [nlogozzo/NickvisionMoney#74]
Since #68, transaction rows have this weird heavy, very not adwaita icon:
![image](https://user-images.githubusercontent.com/27908024/203213051-16d70842-802c-4bd2-aa56-636d5f853915.png)
Any reason to ship this in the first place? a-i-t should have document-edit-symbolic.

**Comment by fsobolev** [comment]
It's actually otherwise, we removed non-adwaita icon. Screenshot from current beta:

![](https://i.imgur.com/hOMOqBk.png)

**Comment by jannuary** [comment]
Hm, alright - closing if fixed on beta.
