### ISSUE TITLE
Add more fine-grained control of repeating transactions

### ISSUE THREAD

**Issue by davidskeck** [nlogozzo/NickvisionMoney#8]
Hello,

I would like to request a finer control over repeating transactions. For example, I get paid every 2 weeks, but there's no way to set a 2 week recurring payment in Money that I have found. I could split my income into two payments and have it work with Money, but it would be nicer to see it come in on schedule as expected.

Thank you!

**Comment by nlogozzo** [comment]
Need to create a schedule widget to create a proper schedule for repeating transactions.
Here is the one from GNU Cash:
![image](https://user-images.githubusercontent.com/17648453/201570188-e1cf4dd8-950a-4963-ad42-433d9c5acb1a.png)

**Comment by nlogozzo** [comment]
We won't be able to get this feature ready in time for V2022.11.1. However, definitely will be included in the next release!

**Comment by davidskeck** [comment]
Thank you!

**Comment by nlogozzo** [comment]
https://github.com/nlogozzo/NickvisionMoney/releases/tag/2023.1.0-beta3
