### ISSUE TITLE
All the missing features...

### ISSUE THREAD

**Issue by RuboGubo** [nlogozzo/NickvisionMoney#90]
So, I was doing my research by talking to my financially engaged associate [Euan Sinnott](https://twitter.com/euanjs), and asked him what he would recommend should be included in the application. I was doing this research for #3, however it quickly turned out that the app itself was already missing a large amount of the standard features that would be required for a tool that could compete with [Intuit's](https://www.intuit.com/) accounting features, or for it to even be usable for most people to manage their personal finances. He gave me the following suggestions:

According to him and some extra research done by me, these are the features that we are currently missing, in order of importance:
- A cross account Dashboard (I should note that there should still be a way to separate accounts, just that it is also useful to have a summary of multiple ones)
- Specific categories for Cash, Assets and Debt:
    - Cash is currently the only supported type.
    - Debt Types (This might be the one most likely to be implemented in the short term, as it is similar to the already implemented Cash feature):
        -  Personal/Secured non-property (e.g. Credit card)
        - Mortgages
        - etc.
    -   Assets should have further default groups for:
        - Stocks
        - Shares
        - Property
        - Luxury Goods
        - etc.
- People's tax bracket, however, this is region dependent and could be complex to define.

To end this all off, I want to note, that this is a very ambitious target, and that I am well aware that I may not be the best person to set the "vision" of the project, but I would like to think that this brief overview of what I and a friend think this app could become is valuable to the developers.

_Sincerely_,
RuboGubo

**Comment by nlogozzo** [comment]
I created a separate issue for "cross account Dashboard" (#162)

That's really the only feature I see that could be added to Money. I don't see Money as being a full "tool that could compete with [Intuit's](https://www.intuit.com/) accounting features." As it's a basic personal...maybe small business...finance manager and not a full accounting suite.

Things like "categories for Cash, Assets and Debt", could be implemented in a user's account file via Groups.
