### ISSUE TITLE
Invalid amount + weird behavior

### ISSUE THREAD

**Issue by stpnwf** [nlogozzo/NickvisionMoney#91]
I just downloaded Money to give it a try, but when I first try to add a transaction I get the problem below:

![Screenshot from 2022-11-27 00-10-32](https://user-images.githubusercontent.com/81482539/204113703-5575f664-ceb6-444d-a21e-5b23c732ed54.png)
Whatever amount I try, it will say it is invalid.
![Screenshot from 2022-11-27 00-11-45](https://user-images.githubusercontent.com/81482539/204113701-ba988590-9370-4000-9dd2-c4793793e14c.png)
But if I do something like 2000.90, then it will just add the .90 as the value; like above.

I tried adding 2000.00, but it still says it is invalid... whatever number I try, it will just add the cents part (if it is > 0).

Money version: 2022.11.1

**Comment by nlogozzo** [comment]
What locale are you in?

**Comment by stpnwf** [comment]
> What locale are you in?

en-US

**Comment by nlogozzo** [comment]
Are you running the Flathub version or manually built?

What OS are you running as well?

**Comment by stpnwf** [comment]
That was installed via flatpak on a live environment of the latest beta of VanillaOS (based on Ubuntu 22.10). 

I just tested it on my machine (en-GB locale, running Zorin OS 16) and I didn't have that issue. An RC for VanillaOS should be released today and I will test it again and report here.

**Comment by nlogozzo** [comment]
> That was installed via flatpak on a live environment of the latest beta of VanillaOS (based on Ubuntu 22.10). 
> 
> I just tested it on my machine (en-GB locale, running Zorin OS 16) and I didn't have that issue. An RC for VanillaOS should be released today and I will test it again and report here.

The problem might be that it's a live environment and therefore there is no user locale for it to report to the application. 
I could set it however where if no locale is found it'll just default to en_us.

**Comment by stpnwf** [comment]
The problem is likely a bug in the RC that the language chosen is not set in the system, if I do it manually it works without an issue. Should be fixed by the time the stable is out Thanks for your time.
