### ISSUE TITLE
[Feature Request] Historical recurring transactions

### ISSUE THREAD

**Issue by kekkoudesu** [nlogozzo/NickvisionMoney#92]
I wanted to input my transactions starting from 1st of January 2022, so I created a weekly transaction starting on the 7th of January. I expected this to create a transaction every week since then until today, but it only creates a single transaction for the 7th of January.

**Comment by fsobolev** [comment]
But you can see in the transaction row "Repeat interval: Weekly", correct?
The problem that numbers in overview are calculated as if all transactions are one-time is known and will be fixed hopefully in next release.

**Comment by kekkoudesu** [comment]
There is only a single transaction that shows on 7th of January (if I go to 14th, 21st, 28th, etc. there isn't anything). This transaction also shows on today's date, which I assume just shows every transaction in the database (because it also shows transactions for future dates). The transaction does say "Repeat Interval: Weekly".

**Comment by nlogozzo** [comment]
Yes, repeating transactions are getting a complete overhaul to fix all it's issues. Please use #8 to track.
