### ISSUE TITLE
Override Currency For Account

### ISSUE THREAD

**Issue by asutoshvariar** [nlogozzo/NickvisionMoney#93]
I'm not in the US, but I have a US locale set. After updating the app to 2022.11.1, I realized that all of my currency values changed to the US dollar. Previously, there was an option to change the currency, but it doesn't seem to be there now. If it's possible, could a manual currency change be reintroduced?

**Comment by nlogozzo** [comment]
The new version of Money now gets the currency information from the user's locale. I will add an option that will allow you to manually change currency options for a specific account.

**Comment by lil5** [comment]
The ability to set the date format would be nice too

**Comment by nlogozzo** [comment]
Use #128 to track.
