### ISSUE TITLE
Localisation issue with real numbers

### ISSUE THREAD

**Issue by zothma** [nlogozzo/NickvisionMoney#97]
I just came across a weird behavior appearing almost every ten cents. Here is an image

![Capture d’écran du 2022-11-27 19-30-41](https://user-images.githubusercontent.com/46780652/204156664-0d7a944b-8e02-4936-ac11-902a06f409a8.png)

From what I tried, the last 0 only disappear with numbers greater than $1 ($0.10, $0.20... appear correctly), every 10 cents except for 0 cents and 50 cents. So, from $0.90 to $1.50, numbers would appear like this (in euros):

![Capture d’écran du 2022-11-27 20-59-46](https://user-images.githubusercontent.com/46780652/204156926-95a42dee-1fc4-435c-8b5e-33e1ab6b182f.png)

**Comment by fsobolev** [comment]
I can reproduce it, will try to fix

**Comment by fsobolev** [comment]
I looked at my screenshot in https://github.com/nlogozzo/NickvisionMoney/pull/124 and found out that this issue was not fixed for all values... 🤔
